package clients.model;

import org.json.JSONException;
import org.json.JSONObject;

public enum TestTypes {
    AAV2("94", "aav2", "Annual test", "Annual test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    AAV3("94", "aav3", "Annual test", "Annual test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    AAV4("94", "aav4", "Annual test", "Annual test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    AAV5("94", "aav5", "Annual test", "Annual test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    AAT1("40", "aat1", "Annual test", "Annual test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    AAT2("94", "aat2", "Annual test", "Annual test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    AAT3("94", "aat3", "Annual test", "Annual test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    AAT4("94", "aat4", "Annual test", "Annual test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    AAT5("94", "aat5", "Annual test", "Annual test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
//    commented test types are not yet added in the test-types.json file
//    TGV2("40", "tgv2", TestTypeClassification.CERTIFICATE.getValue()),
//    TGV3("40", "tgv3", TestTypeClassification.CERTIFICATE.getValue()),
//    TGV4("40", "tgv4", TestTypeClassification.CERTIFICATE.getValue()),
    FFV2("95", "ffv2", "First test", "First test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    FFV3("95", "ffv3", "First test", "First test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    FFV4("95", "ffv4", "First test", "First test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    FFV5("95", "ffv5", "First test", "First test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    FFT1("41", "fft1", "First test", "First test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    FFT2("95", "fft2", "First test", "First test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    FFT3("95", "fft3", "First test", "First test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    FFT4("95", "fft4", "First test", "First test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    FFT5("95", "fft5", "First test", "First test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
//    FGV2("40", "fgv2", TestTypeClassification.CERTIFICATE.getValue()),
//    FGV3("40", "fgv3", TestTypeClassification.CERTIFICATE.getValue()),
//    FGV4("40", "fgv4", TestTypeClassification.CERTIFICATE.getValue()),
    LDV("44", "ldv", "LEC", "Low Emissions Certificate (LEC) with annual test",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    LEV("45", "lev", "LEC", "Low Emissions Certificate (LEC)",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    NFV("47", "nfv", "Notifiable alteration", "Free notifiable alteration",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    NFT("47", "nft", "Notifiable alteration", "Free notifiable alteration",
            "{\"vehicleType\":\"trl\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    NVV("48", "nvv", "Paid", "Paid notifiable alteration",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    NVT("48", "nvt", "Paid", "Paid notifiable alteration",
            "{\"vehicleType\":\"trl\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    TIV("49", "tiv", "TIR", "TIR test",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    TIT("49", "tit", "TIR", "TIR test",
            "{\"vehicleType\":\"trl\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    DDV("50", "ddv", "ADR", "ADR test",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    DDT("50", "ddt", "ADR", "ADR test",
            "{\"vehicleType\":\"trl\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    RPV2("53", "rpv2", "Paid", "Paid annual test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    RPV3("53", "rpv3", "Paid", "Paid annual test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    RPV4("53", "rpv4", "Paid", "Paid annual test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    RPV5("53", "rpv5", "Paid", "Paid annual test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    RPT1("98", "rpt1", "Paid", "Paid annual test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    RPT2("53", "rpt2", "Paid", "Paid annual test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    RPT3("53", "rpt3", "Paid", "Paid annual test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    RPT4("53", "rpt4", "Paid", "Paid annual test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    RPT5("53", "rpt5", "Paid", "Paid annual test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
//    PGV2("40", "pgv2", TestTypeClassification.CERTIFICATE.getValue()),
//    PGV3("40", "pgv3", TestTypeClassification.CERTIFICATE.getValue()),
//    PGV4("40", "pgv4", TestTypeClassification.CERTIFICATE.getValue()),
    RSV2("54", "rsv2", "Part paid", "Part paid annual test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    RSV3("54", "rsv3", "Part paid", "Part paid annual test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    RSV4("54", "rsv4", "Part paid", "Part paid annual test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    RSV5("54", "rsv5", "Part paid", "Part paid annual test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    RST1("99", "rst1", "Part paid", "Part paid annual test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    RST2("54", "rst2", "Part paid", "Part paid annual test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    RST3("54", "rst3", "Part paid", "Part paid annual test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    RST4("54", "rst4", "Part paid", "Part paid annual test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    RST5("54", "rst5", "Part paid", "Part paid annual test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
//    PTV2("40", "tgv2", TestTypeClassification.CERTIFICATE.getValue()),
//    PTV3("40", "tgv3", TestTypeClassification.CERTIFICATE.getValue()),
//    PTV4("40", "tgv4", TestTypeClassification.CERTIFICATE.getValue()),
    TRV("56", "trv", "Paid", "Paid TIR retest",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    TRT("56", "trt", "Paid", "Paid TIR retest",
            "{\"vehicleType\":\"trl\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    RFT("57", "rft", "Free", "Free TIR retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    ARV("59", "arv", "Paid", "Paid ADR retest",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    ART("59", "art", "Paid", "Paid ADR retest",
            "{\"vehicleType\":\"trl\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    DRV("60", "drv", "Free", "Free ADR retest",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    DRT("60", "drt", "Free", "Free ADR retest",
            "{\"vehicleType\":\"trl\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QKV("62", "qkv", "Paid", "Paid roadworthiness retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    MDA("100", "mda", "Vitesse 100 Replacement", "Vitesse 100 Replacement",
            "{\"vehicleType\":\"psv\"}", TestTypeClassification.NON_ANUAL.getValue()),
    MDU("121", "mdu", "Vitesse 100 Application", "Vitesse 100 Application",
            "{\"vehicleType\":\"psv\"}", TestTypeClassification.NON_ANUAL.getValue()),
    QKT("101", "qkt", "Paid", "Paid roadworthiness retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    QPV("62", "qpv", "Paid", "Paid roadworthiness retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    QPT("62", "qpt", "Paid", "Paid roadworthiness retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    QQV("62", "qqv", "Paid", "Paid roadworthiness retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    QQT("62", "qqt", "Paid", "Paid roadworthiness retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    RUV("63", "ruv", "Part Paid", "Part paid roadworthiness retest",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.CERTIFICATE.getValue()),
    RUT("63", "rut", "Part Paid", "Part paid roadworthiness retest",
            "{\"vehicleType\":\"trl\"}", TestTypeClassification.CERTIFICATE.getValue()),
    RGV2("65", "rgv2", "Paid", "Paid first test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    RGV3("65", "rgv3", "Paid", "Paid first test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    RGV4("65", "rgv4", "Paid", "Paid first test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    RGV5("65", "rgv5", "Paid", "Paid first test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    RGT1("103", "rgt1", "Paid", "Paid first test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    RGT2("65", "rgt2", "Paid", "Paid first test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    RGT3("65", "rgt3", "Paid", "Paid first test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    RGT4("65", "rgt4", "Paid", "Paid first test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    RGT5("65", "rgt5", "Paid", "Paid first test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    RIV2("66", "riv2", "Part paid", "Part paid first test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    RIV3("66", "riv3", "Part paid", "Part paid first test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    RIV4("66", "riv4", "Part paid", "Part paid first test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    RIV5("66", "riv5", "Part paid", "Part paid first test retest",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    RIT1("104", "rit1", "Part paid", "Part paid first test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    RIT2("66", "rit2", "Part paid", "Part paid first test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    RIT3("66", "rit3", "Part paid", "Part paid first test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    RIT4("66", "rit4", "Part paid", "Part paid first test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    RIT5("66", "rit5", "Part paid", "Part paid first test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    RHT("67", "rht", "Free", "Free first test retest",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    P1V2("70", "p1v2", "With certification", "Paid prohibition clearance (full inspection with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    P1V3("70", "p1v3", "With certification", "Paid prohibition clearance (full inspection with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    P1V4("70", "p1v4", "With certification", "Paid prohibition clearance (full inspection with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    P1V5("70", "p1v5", "With certification", "Paid prohibition clearance (full inspection with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    P1T1("107", "p1t1", "With certification", "Paid prohibition clearance (full inspection with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    P1T2("70", "p1t2", "With certification", "Paid prohibition clearance (full inspection with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    P1T3("70", "p1t3", "With certification", "Paid prohibition clearance (full inspection with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    P1T4("70", "p1t4", "With certification", "Paid prohibition clearance (full inspection with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    P1T5("70", "p1t5", "With certification", "Paid prohibition clearance (full inspection with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    PBV2("71", "pbv2", "Without certification", "Paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PBV3("71", "pbv3", "Without certification", "Paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PBV4("71", "pbv4", "Without certification", "Paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PBV5("71", "pbv5", "Without certification", "Paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PBT1("108", "pbt1", "Without certification", "Paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PBT2("71", "pbt2", "Without certification", "Paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PBT3("71", "pbt3", "Without certification", "Paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PBT4("71", "pbt4", "Without certification", "Paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PBT5("71", "pbt5", "Without certification", "Paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    POV2("72", "pov2", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    POV3("72", "pov3", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    POV4("72", "pov4", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    POV5("72", "pov5", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    POT1("109", "pot1", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    POT2("72", "pot2", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    POT3("72", "pot3", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    POT4("72", "pot4", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    POT5("72", "pot5", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (full inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PAV2("73", "pav2", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (part inspection without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PAV3("73", "pav3", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (part inspection without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PAV4("73", "pav4", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (part inspection without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PAV5("73", "pav5", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (part inspection without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PAT1("110", "pat1", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (part inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PAT2("73", "pat2", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (part inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PAT3("73", "pat3", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (part inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PAT4("73", "pat4", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (part inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PAT5("73", "pat5", "Full inspection/ Part Fee - Without certification", "Part paid prohibition clearance (part inspection without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    P3V2("76", "p3v2", "With certification", "Paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    P3V3("76", "p3v3", "With certification", "Paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    P3V4("76", "p3v4", "With certification", "Paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    P3V5("76", "p3v5", "With certification", "Paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    P3T1("113", "p3t1", "With certification", "Paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    P3T2("76", "p3t2", "With certification", "Paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    P3T3("76", "p3t3", "With certification", "Paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    P3T4("76", "p3t4", "With certification", "Paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    P3T5("76", "p3t5", "With certification", "Paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    PFV2("77", "pfv2", "Without certification", "Paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PFV3("77", "pfv3", "Without certification", "Paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PFV4("77", "pfv4", "Without certification", "Paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PFV5("77", "pfv5", "Without certification", "Paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PFT1("114", "pft1", "Without certification", "Paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PFT2("77", "pft2", "Without certification", "Paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PFT3("77", "pft3", "Without certification", "Paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PFT4("77", "pft4", "Without certification", "Paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PFT5("77", "pft5", "Without certification", "Paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    P6V2("79", "p6v2", "With certification", "Part paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    P6V3("79", "p6v3", "With certification", "Part paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    P6V4("79", "p6v4", "With certification", "Part paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    P6V5("79", "p6v5", "With certification", "Part paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    P6T1("116", "p6t1", "With certification", "Part paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    P6T2("79", "p6t2", "With certification", "Part paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    P6T3("79", "p6t3", "With certification", "Part paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    P6T4("79", "p6t4", "With certification", "Part paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    P6T5("79", "p6t5", "With certification", "Part paid prohibition clearance (retest with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    P2V2("80", "p2v2", "Without certification", "Part paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    P2V3("80", "p2v3", "Without certification", "Part paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    P2V4("80", "p2v4", "Without certification", "Part paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    P2V5("80", "p2v5", "Without certification", "Part paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    P2T1("117", "p2t1", "Without certification", "Part paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    P2T2("80", "p2t2", "Without certification", "Part paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    P2T3("80", "p2t3", "Without certification", "Part paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    P2T4("80", "p2t4", "Without certification", "Part paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    P2T5("80", "p2t5", "Without certification", "Part paid prohibition clearance (retest without certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    P7V2("82", "p7v2", "Full Inspection/ Fee - With certification", "Paid prohibition clearance on first test (full inspection with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    P7V3("82", "p7v3", "Full Inspection/ Fee - With certification", "Paid prohibition clearance on first test (full inspection with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    P7V4("82", "p7v4", "Full Inspection/ Fee - With certification", "Paid prohibition clearance on first test (full inspection with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    P7V5("82", "p7v5", "Full Inspection/ Fee - With certification", "Paid prohibition clearance on first test (full inspection with certification)",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    P7T1("119", "p7t1", "Full Inspection/ Fee - With certification", "Paid prohibition clearance on first test (full inspection with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    P7T2("82", "p7t2", "Full Inspection/ Fee - With certification", "Paid prohibition clearance on first test (full inspection with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    P7T3("82", "p7t3", "Full Inspection/ Fee - With certification", "Paid prohibition clearance on first test (full inspection with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    P7T4("82", "p7t4", "Full Inspection/ Fee - With certification", "Paid prohibition clearance on first test (full inspection with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    P7T5("82", "p7t5", "Full Inspection/ Fee - With certification", "Paid prohibition clearance on first test (full inspection with certification)",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    P4V2("83", "p4v2", "Retest - Paid", "Paid retest prohibition clearance on first test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    P4V3("83", "p4v3", "Retest - Paid", "Paid retest prohibition clearance on first test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    P4V4("83", "p4v4", "Retest - Paid", "Paid retest prohibition clearance on first test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    P4V5("83", "p4v5", "Retest - Paid", "Paid retest prohibition clearance on first test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    P4T1("120", "p4t1", "Retest - Paid", "Paid retest prohibition clearance on first test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    P4T2("83", "p4t2", "Retest - Paid", "Paid retest prohibition clearance on first test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    P4T3("83", "p4t3", "Retest - Paid", "Paid retest prohibition clearance on first test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    P4T4("83", "p4t4", "Retest - Paid", "Paid retest prohibition clearance on first test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    P4T5("83", "p4t5", "Retest - Paid", "Paid retest prohibition clearance on first test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    BIB("85", "bib", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":1}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QAV2("85", "qav2", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QAV3("85", "qav3", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QAV4("85", "qav4", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QAV5("85", "qav5", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QAT1("85", "qat1", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QAT2("85", "qat2", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QAT3("85", "qat3", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QAT4("85", "qat4", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QAT5("85", "qat5", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QBV("86", "qbv", "Multi - check", "Voluntary multi-check",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    BID_HGV("87", "bid", "Shaker plate check", "Voluntary Shaker plate check",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    BID_TRL("87", "bid", "Shaker plate check", "Voluntary Shaker plate check",
            "{\"vehicleType\":\"trl\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    BIF_HGV("88", "bif", "Speed limiter check", "Voluntary Speed limiter check",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QCV("89", "qcv", "Smoke test", "Voluntary smoke test",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QDV("90", "qdv", "Headlamp aim test", "Voluntary headlamp aim test",
            "{\"vehicleType\":\"hgv\"}", TestTypeClassification.NO_CERTIFICATE.getValue()),
    QJV2("122", "qjv2", "Roadworthiness test", "Voluntary roadworthiness test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    QJV3("122", "qjv3", "Roadworthiness test", "Voluntary roadworthiness test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    QJV4("122", "qjv4", "Roadworthiness test", "Voluntary roadworthiness test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    QJV5("122", "qjv5", "Roadworthiness test", "Voluntary roadworthiness test",
            "{\"vehicleType\":\"hgv\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    QJT1("91", "qjt1", "Roadworthiness test", "Voluntary roadworthiness test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":1}", TestTypeClassification.CERTIFICATE.getValue()),
    QJT2("122", "qjt2", "Roadworthiness test", "Voluntary roadworthiness test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":2}", TestTypeClassification.CERTIFICATE.getValue()),
    QJT3("122", "qjt3", "Roadworthiness test", "Voluntary roadworthiness test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":3}", TestTypeClassification.CERTIFICATE.getValue()),
    QJT4("122", "qjt4", "Roadworthiness test", "Voluntary roadworthiness test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":4}", TestTypeClassification.CERTIFICATE.getValue()),
    QJT5("122", "qjt5", "Roadworthiness test", "Voluntary roadworthiness test",
            "{\"vehicleType\":\"trl\", \"noOfAxles\":5}", TestTypeClassification.CERTIFICATE.getValue()),
    AAL("1", "aal", "Annual test", "Annual test",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    AAS("1", "aas", "Annual test", "Annual test",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    ADL("1", "adl", "Annual test", "Annual test",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    WDL("3", "wdl", "Annual test", "Class 6A seatbelt installation check (annual test)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    WDS("3", "wds", "Annual test", "Class 6A seatbelt installation check (annual test)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    WBL("4", "wbl", "First test", "Class 6A seatbelt installation check (first test)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    WBS("4", "wbs", "First test", "Class 6A seatbelt installation check (first test)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    RHL("7", "rhl", "Any PSV", "Paid retest",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    RPL("7", "rpl", "Any PSV", "Paid retest",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    RPS("7", "rps", "Any PSV", "Paid retest",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    WHL("8", "whl", "Class 6A (seatbelt installation check)", "Paid retest with Class 6A seatbelt installation check",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    WHS("8", "whs", "Class 6A (seatbelt installation check)", "Paid retest with Class 6A seatbelt installation check",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    RGL("10", "rgl", "Any PSV", "Part-paid retest",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    RSL("10", "rsl", "Any PSV", "Part-paid retest",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    RSS("10", "rss", "Any PSV", "Part-paid retest",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    PHL("15", "phl", "Without certification", "Paid prohibition clearance (full inspection without certificate)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    PHS("15", "phs", "Without certification", "Paid prohibition clearance (full inspection without certificate)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    P1L("14", "p1l", "With certification", "Paid prohibition clearance (full inspection with certificate)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    P1S("14", "p1s", "With certification", "Paid prohibition clearance (full inspection with certificate)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    P8L("18", "p8l", "With certification", "Paid prohibition clearance (retest with certificate)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    P8S("18", "p8s", "With certification", "Paid prohibition clearance (retest with certificate)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    PML("19", "pml", "Without certification", "Paid prohibition clearance (retest without certificate)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    PMS("19", "pms", "Without certification", "Paid prohibition clearance (retest without certificate)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    P6L("21", "p6l", "With certification", "Part-paid prohibition clearance (retest with certificate)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    P6S("21", "p6s", "With certification", "Part-paid prohibition clearance (retest with certificate)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    P2L("22", "p2l", "Without certification", "Part-paid prohibition clearance (retest without certificate)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    P2S("22", "p2s", "Without certification", "Part-paid prohibition clearance (retest without certificate)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
//    P3L("14", "p3l", TestTypeClassification.NO_CERTIFICATE.getValue()),
    PGL("23", "pgl", "Part inspection/ part fee", "Part-paid prohibition clearance (partial inspection)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
        TestTypeClassification.NO_CERTIFICATE.getValue()),
    PGS("23", "pgs", "Part inspection/ part fee", "Part-paid prohibition clearance (partial inspection)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    PRL("16", "prl", "Full inspection/ part fee", "Part-paid prohibition clearance (full inspection)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    PRS("16", "prs", "Full inspection/ part fee", "Part-paid prohibition clearance (full inspection)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    WIL("28", "wil", "PG9 retest", "Prohibition clearance (retest with Class 6A seatbelt installation check)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    WIS("28", "wis", "PG9 retest", "Prohibition clearance (retest with Class 6A seatbelt installation check)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    WEL("93", "wfl", "Full inspection / full fee", "Paid prohibition clearance with Class 6A seatbelt installation check (full inspection)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    WES("93", "wfs", "Full inspection / full fee", "Paid prohibition clearance with Class 6A seatbelt installation check (full inspection)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NO_CERTIFICATE.getValue()),
    QAL("30", "qal", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"psv\", \"noOfAxles\":2, \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    QAS("30", "qas", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"psv\", \"noOfAxles\":2, \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    QGL("30", "qgl", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"psv\", \"noOfAxles\":3, \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    QGS("30", "qgs", "Brake test", "Voluntary brake test",
            "{\"vehicleType\":\"psv\", \"noOfAxles\":3, \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    QDL("31", "qdl", "Headlamp aim test", "Voluntary headlamp aim check",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    QDS("31", "qds", "Headlamp aim test", "Voluntary headlamp aim check",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    QCL("32", "qcl", "Smoke test", "Voluntary smoke test",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    QCS("32", "qcs", "Smoke test", "Voluntary smoke test",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    QBL("33", "qbl", "Multi - check", "Voluntary multi check (headlamp aim, smoke and brake test)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    QBS("33", "qbs", "Multi - check", "Voluntary multi check (headlamp aim, smoke and brake test)",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    BIF_PSV("34", "bif_psv", "Speed limiter check", "Voluntary speed limiter check",
            "{\"vehicleType\":\"psv\", \"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    TEL("36", "tel", "Tempo 100", "Voluntary Tempo 100",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    TES("36", "tes", "Tempo 100", "Voluntary Tempo 100",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    NFL("38", "nfl", "Notifiable alteration", "Notifiable alteration check",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"large\",\"vehicleConfiguration\":\"rigid\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
    NFS("38", "nfs", "Notifiable alteration", "Notifiable alteration check",
            "{\"vehicleType\":\"psv\", \"vehicleSize\":\"small\",\"vehicleConfiguration\":\"articulated\"}",
            TestTypeClassification.NON_ANUAL.getValue()),
//    LCP("39", "lcp", TestTypeClassification.NO_CERTIFICATE.getValue()),
    LBP("39", "lbp", "LEC", "Low Emissions Certificate (LEC) with annual test",
            "{\"vehicleType\":\"psv\", \"vehicleConfiguration\":\"rigid\"}", TestTypeClassification.NON_ANUAL.getValue());

    private final String id;
    private final String testCode;
    private final String name;
    private final String testTypeName;
    private final String restrictions;
    private final String classification;

    TestTypes(String id, String testCode, String name, String testTypeName, String restrictions, String classification) {
        this.id = id;
        this.testCode = testCode;
        this.name = name;
        this.testTypeName = testTypeName;
        this.restrictions = restrictions;
        this.classification = classification;
    }

    public String getTestCode() {
        return testCode;
    }

    public String getName() {
        return name;
    }

    public String getTestTypeName() {
        return testTypeName;
    }

    public JSONObject getRestrictions() throws JSONException {
        return new JSONObject(restrictions);
    }

    public String getClassification() {
        return classification;
    }

    public String getId() {
        return id;
    }
}