package vott.models.dao;

import lombok.Data;

@Data
public class TechnicalRecord {

    private String vehicleID;
    private String recordCompleteness;
    private String createdAt;
    private String lastUpdatedAt;
    private String makeModelID;
    private String functionCode;
    private String offRoad;
    private String numberOfWheelsDriven;
    private String emissionsLimit;
    private String departmentalVehicleMarker;
    private String alterationMarker;
    private String vehicleClassID;
    private String variantVersionNumber;
    private String grossEecWeight;
    private String trainEecWeight;
    private String maxTrainEecWeight;
    private String applicantDetailID;
    private String purchaserDetailID;
    private String manufacturerDetailID;
    private String manufactureYear;
    private String regnDate;
    private String firstUseDate;
    private String coifDate;
    private String ntaNumber;
    private String coifSerialNumber;
    private String coifCertifierName;
    private String approvalType;
    private String approvalTypeNumber;
    private String variantNumber;
    private String conversionRefNo;
    private String seatsLowerDeck;
    private String seatsUpperDeck;
    private String standingCapacity;
    private String speedRestriction;
    private String speedLimiterMrk;
    private String tachoExemptMrk;
    private String dispensations;
    private String remarks;
    private String reasonForCreation;
    private String statusCode;
    private String unladenWeight;
    private String grossKerbWeight;
    private String grossLadenWeight;
    private String grossGbWeight;
    private String grossDesignWeight;
    private String trainGbWeight;
    private String trainDesignWeight;
    private String maxTrainGbWeight;
    private String maxTrainDesignWeight;
    private String maxLoadOnCoupling;
    private String frameDescription;
    private String tyreUseCode;
    private String roadFriendly;
    private String drawbarCouplingFitted;
    private String euroStandard;
    private String suspensionType;
    private String couplingType;
    private String length;
    private String height;
    private String width;
    private String frontAxleTo5thWheelMin;
    private String frontAxleTo5thWheelMax;
    private String frontAxleTo5thWheelCouplingMin;
    private String frontAxleTo5thWheelCouplingMax;
    private String frontAxleToRearAxle;
    private String rearAxleToRearTrl;
    private String couplingCenterToRearAxleMin;
    private String couplingCenterToRearAxleMax;
    private String couplingCenterToRearTrlMin;
    private String couplingCenterToRearTrlMax;
    private String centreOfRearmostAxleToRearOfTrl;
    private String notes;
    private String purchaserNotes;
    private String manufacturerNotes;
    private String noOfAxles;
    private String brakeCode;
    private String brakes_dtpNumber;
    private String brakes_loadSensingValve;
    private String brakes_antilockBrakingSystem;
    private String createdByID;
    private String lastUpdatedByID;
    private String updateType;
    private String numberOfSeatbelts;
    private String seatbeltInstallationApprovalDate;

}
