/*
 * Vehicle Enquiry Service Swagger
 * This is the CVS API for showing details of heavy goods vehicles and their associated test result.
 *
 * OpenAPI spec version: 1.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.enquiry;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * Defect
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T17:16:44.237Z[GMT]")
public class Defect {
  @SerializedName("imNumber")
  private Integer imNumber = null;

  @SerializedName("imDescription")
  private String imDescription = null;

  @SerializedName("itemNumber")
  private Integer itemNumber = null;

  @SerializedName("itemDescription")
  private String itemDescription = null;

  @SerializedName("deficiencyRef")
  private String deficiencyRef = null;

  @SerializedName("deficiencyId")
  private String deficiencyId = null;

  @SerializedName("deficiencySubId")
  private String deficiencySubId = null;

  @SerializedName("deficiencyCategory")
  private String deficiencyCategory = null;

  @SerializedName("deficiencyText")
  private String deficiencyText = null;

  @SerializedName("stdForProhibition")
  private Boolean stdForProhibition = null;

  public Defect imNumber(Integer imNumber) {
    this.imNumber = imNumber;
    return this;
  }

   /**
   * Get imNumber
   * @return imNumber
  **/
  public Integer getImNumber() {
    return imNumber;
  }

  public void setImNumber(Integer imNumber) {
    this.imNumber = imNumber;
  }

  public Defect imDescription(String imDescription) {
    this.imDescription = imDescription;
    return this;
  }

   /**
   * Get imDescription
   * @return imDescription
  **/
  public String getImDescription() {
    return imDescription;
  }

  public void setImDescription(String imDescription) {
    this.imDescription = imDescription;
  }

  public Defect itemNumber(Integer itemNumber) {
    this.itemNumber = itemNumber;
    return this;
  }

   /**
   * Get itemNumber
   * @return itemNumber
  **/
  public Integer getItemNumber() {
    return itemNumber;
  }

  public void setItemNumber(Integer itemNumber) {
    this.itemNumber = itemNumber;
  }

  public Defect itemDescription(String itemDescription) {
    this.itemDescription = itemDescription;
    return this;
  }

   /**
   * Get itemDescription
   * @return itemDescription
  **/
  public String getItemDescription() {
    return itemDescription;
  }

  public void setItemDescription(String itemDescription) {
    this.itemDescription = itemDescription;
  }

  public Defect deficiencyRef(String deficiencyRef) {
    this.deficiencyRef = deficiencyRef;
    return this;
  }

   /**
   * Get deficiencyRef
   * @return deficiencyRef
  **/
  public String getDeficiencyRef() {
    return deficiencyRef;
  }

  public void setDeficiencyRef(String deficiencyRef) {
    this.deficiencyRef = deficiencyRef;
  }

  public Defect deficiencyId(String deficiencyId) {
    this.deficiencyId = deficiencyId;
    return this;
  }

   /**
   * Get deficiencyId
   * @return deficiencyId
  **/
  public String getDeficiencyId() {
    return deficiencyId;
  }

  public void setDeficiencyId(String deficiencyId) {
    this.deficiencyId = deficiencyId;
  }

  public Defect deficiencySubId(String deficiencySubId) {
    this.deficiencySubId = deficiencySubId;
    return this;
  }

   /**
   * Get deficiencySubId
   * @return deficiencySubId
  **/
  public String getDeficiencySubId() {
    return deficiencySubId;
  }

  public void setDeficiencySubId(String deficiencySubId) {
    this.deficiencySubId = deficiencySubId;
  }

  public Defect deficiencyCategory(String deficiencyCategory) {
    this.deficiencyCategory = deficiencyCategory;
    return this;
  }

   /**
   * Get deficiencyCategory
   * @return deficiencyCategory
  **/
  public String getDeficiencyCategory() {
    return deficiencyCategory;
  }

  public void setDeficiencyCategory(String deficiencyCategory) {
    this.deficiencyCategory = deficiencyCategory;
  }

  public Defect deficiencyText(String deficiencyText) {
    this.deficiencyText = deficiencyText;
    return this;
  }

   /**
   * Get deficiencyText
   * @return deficiencyText
  **/
  public String getDeficiencyText() {
    return deficiencyText;
  }

  public void setDeficiencyText(String deficiencyText) {
    this.deficiencyText = deficiencyText;
  }

  public Defect stdForProhibition(Boolean stdForProhibition) {
    this.stdForProhibition = stdForProhibition;
    return this;
  }

   /**
   * Get stdForProhibition
   * @return stdForProhibition
  **/
  public Boolean isStdForProhibition() {
    return stdForProhibition;
  }

  public void setStdForProhibition(Boolean stdForProhibition) {
    this.stdForProhibition = stdForProhibition;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Defect defect = (Defect) o;
    return Objects.equals(this.imNumber, defect.imNumber) &&
        Objects.equals(this.imDescription, defect.imDescription) &&
        Objects.equals(this.itemNumber, defect.itemNumber) &&
        Objects.equals(this.itemDescription, defect.itemDescription) &&
        Objects.equals(this.deficiencyRef, defect.deficiencyRef) &&
        Objects.equals(this.deficiencyId, defect.deficiencyId) &&
        Objects.equals(this.deficiencySubId, defect.deficiencySubId) &&
        Objects.equals(this.deficiencyCategory, defect.deficiencyCategory) &&
        Objects.equals(this.deficiencyText, defect.deficiencyText) &&
        Objects.equals(this.stdForProhibition, defect.stdForProhibition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imNumber, imDescription, itemNumber, itemDescription, deficiencyRef, deficiencyId, deficiencySubId, deficiencyCategory, deficiencyText, stdForProhibition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Defect {\n");
    
    sb.append("    imNumber: ").append(toIndentedString(imNumber)).append("\n");
    sb.append("    imDescription: ").append(toIndentedString(imDescription)).append("\n");
    sb.append("    itemNumber: ").append(toIndentedString(itemNumber)).append("\n");
    sb.append("    itemDescription: ").append(toIndentedString(itemDescription)).append("\n");
    sb.append("    deficiencyRef: ").append(toIndentedString(deficiencyRef)).append("\n");
    sb.append("    deficiencyId: ").append(toIndentedString(deficiencyId)).append("\n");
    sb.append("    deficiencySubId: ").append(toIndentedString(deficiencySubId)).append("\n");
    sb.append("    deficiencyCategory: ").append(toIndentedString(deficiencyCategory)).append("\n");
    sb.append("    deficiencyText: ").append(toIndentedString(deficiencyText)).append("\n");
    sb.append("    stdForProhibition: ").append(toIndentedString(stdForProhibition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
