/*
 * Vehicle Enquiry Service Swagger
 * This is the CVS API for showing details of heavy goods vehicles and their associated test result.
 *
 * OpenAPI spec version: 1.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.enquiry;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * FuelEmission
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T17:16:44.237Z[GMT]")
public class FuelEmission {
  @SerializedName("modTypeCode")
  private String modTypeCode = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("emissionStandard")
  private String emissionStandard = null;

  @SerializedName("fuelType")
  private String fuelType = null;

  public FuelEmission modTypeCode(String modTypeCode) {
    this.modTypeCode = modTypeCode;
    return this;
  }

   /**
   * Get modTypeCode
   * @return modTypeCode
  **/
  public String getModTypeCode() {
    return modTypeCode;
  }

  public void setModTypeCode(String modTypeCode) {
    this.modTypeCode = modTypeCode;
  }

  public FuelEmission description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public FuelEmission emissionStandard(String emissionStandard) {
    this.emissionStandard = emissionStandard;
    return this;
  }

   /**
   * Get emissionStandard
   * @return emissionStandard
  **/
  public String getEmissionStandard() {
    return emissionStandard;
  }

  public void setEmissionStandard(String emissionStandard) {
    this.emissionStandard = emissionStandard;
  }

  public FuelEmission fuelType(String fuelType) {
    this.fuelType = fuelType;
    return this;
  }

   /**
   * Get fuelType
   * @return fuelType
  **/
  public String getFuelType() {
    return fuelType;
  }

  public void setFuelType(String fuelType) {
    this.fuelType = fuelType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FuelEmission fuelEmission = (FuelEmission) o;
    return Objects.equals(this.modTypeCode, fuelEmission.modTypeCode) &&
        Objects.equals(this.description, fuelEmission.description) &&
        Objects.equals(this.emissionStandard, fuelEmission.emissionStandard) &&
        Objects.equals(this.fuelType, fuelEmission.fuelType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modTypeCode, description, emissionStandard, fuelType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FuelEmission {\n");
    
    sb.append("    modTypeCode: ").append(toIndentedString(modTypeCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    emissionStandard: ").append(toIndentedString(emissionStandard)).append("\n");
    sb.append("    fuelType: ").append(toIndentedString(fuelType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
