/*
 * Vehicle Enquiry Service Swagger
 * This is the CVS API for showing details of heavy goods vehicles and their associated test result.
 *
 * OpenAPI spec version: 1.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.enquiry;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * Location
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T17:16:44.237Z[GMT]")
public class Location {
  @SerializedName("vertical")
  private String vertical = null;

  @SerializedName("horizontal")
  private String horizontal = null;

  @SerializedName("lateral")
  private Integer lateral = null;

  @SerializedName("longitudinal")
  private Integer longitudinal = null;

  @SerializedName("rowNumber")
  private Integer rowNumber = null;

  @SerializedName("seatNumber")
  private Integer seatNumber = null;

  @SerializedName("axleNumber")
  private Integer axleNumber = null;

  public Location vertical(String vertical) {
    this.vertical = vertical;
    return this;
  }

   /**
   * Get vertical
   * @return vertical
  **/
  public String getVertical() {
    return vertical;
  }

  public void setVertical(String vertical) {
    this.vertical = vertical;
  }

  public Location horizontal(String horizontal) {
    this.horizontal = horizontal;
    return this;
  }

   /**
   * Get horizontal
   * @return horizontal
  **/
  public String getHorizontal() {
    return horizontal;
  }

  public void setHorizontal(String horizontal) {
    this.horizontal = horizontal;
  }

  public Location lateral(Integer lateral) {
    this.lateral = lateral;
    return this;
  }

   /**
   * Get lateral
   * @return lateral
  **/
  public Integer getLateral() {
    return lateral;
  }

  public void setLateral(Integer lateral) {
    this.lateral = lateral;
  }

  public Location longitudinal(Integer longitudinal) {
    this.longitudinal = longitudinal;
    return this;
  }

   /**
   * Get longitudinal
   * @return longitudinal
  **/
  public Integer getLongitudinal() {
    return longitudinal;
  }

  public void setLongitudinal(Integer longitudinal) {
    this.longitudinal = longitudinal;
  }

  public Location rowNumber(Integer rowNumber) {
    this.rowNumber = rowNumber;
    return this;
  }

   /**
   * Get rowNumber
   * @return rowNumber
  **/
  public Integer getRowNumber() {
    return rowNumber;
  }

  public void setRowNumber(Integer rowNumber) {
    this.rowNumber = rowNumber;
  }

  public Location seatNumber(Integer seatNumber) {
    this.seatNumber = seatNumber;
    return this;
  }

   /**
   * Get seatNumber
   * @return seatNumber
  **/
  public Integer getSeatNumber() {
    return seatNumber;
  }

  public void setSeatNumber(Integer seatNumber) {
    this.seatNumber = seatNumber;
  }

  public Location axleNumber(Integer axleNumber) {
    this.axleNumber = axleNumber;
    return this;
  }

   /**
   * Get axleNumber
   * @return axleNumber
  **/
  public Integer getAxleNumber() {
    return axleNumber;
  }

  public void setAxleNumber(Integer axleNumber) {
    this.axleNumber = axleNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Location location = (Location) o;
    return Objects.equals(this.vertical, location.vertical) &&
        Objects.equals(this.horizontal, location.horizontal) &&
        Objects.equals(this.lateral, location.lateral) &&
        Objects.equals(this.longitudinal, location.longitudinal) &&
        Objects.equals(this.rowNumber, location.rowNumber) &&
        Objects.equals(this.seatNumber, location.seatNumber) &&
        Objects.equals(this.axleNumber, location.axleNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vertical, horizontal, lateral, longitudinal, rowNumber, seatNumber, axleNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Location {\n");
    
    sb.append("    vertical: ").append(toIndentedString(vertical)).append("\n");
    sb.append("    horizontal: ").append(toIndentedString(horizontal)).append("\n");
    sb.append("    lateral: ").append(toIndentedString(lateral)).append("\n");
    sb.append("    longitudinal: ").append(toIndentedString(longitudinal)).append("\n");
    sb.append("    rowNumber: ").append(toIndentedString(rowNumber)).append("\n");
    sb.append("    seatNumber: ").append(toIndentedString(seatNumber)).append("\n");
    sb.append("    axleNumber: ").append(toIndentedString(axleNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
