/*
 * Vehicle Enquiry Service Swagger
 * This is the CVS API for showing details of heavy goods vehicles and their associated test result.
 *
 * OpenAPI spec version: 1.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.enquiry;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * MakeModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T17:16:44.237Z[GMT]")
public class MakeModel {
  @SerializedName("make")
  private String make = null;

  @SerializedName("model")
  private String model = null;

  @SerializedName("chassisMake")
  private String chassisMake = null;

  @SerializedName("chassisModel")
  private String chassisModel = null;

  @SerializedName("bodyMake")
  private String bodyMake = null;

  @SerializedName("bodyModel")
  private String bodyModel = null;

  @SerializedName("modelLiteral")
  private String modelLiteral = null;

  @SerializedName("bodyTypeCode")
  private String bodyTypeCode = null;

  @SerializedName("bodyTypeDescription")
  private String bodyTypeDescription = null;

  @SerializedName("fuelPropulsionSystem")
  private String fuelPropulsionSystem = null;

  public MakeModel make(String make) {
    this.make = make;
    return this;
  }

   /**
   * ALL
   * @return make
  **/
  public String getMake() {
    return make;
  }

  public void setMake(String make) {
    this.make = make;
  }

  public MakeModel model(String model) {
    this.model = model;
    return this;
  }

   /**
   * ALL
   * @return model
  **/
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public MakeModel chassisMake(String chassisMake) {
    this.chassisMake = chassisMake;
    return this;
  }

   /**
   * ALL
   * @return chassisMake
  **/
  public String getChassisMake() {
    return chassisMake;
  }

  public void setChassisMake(String chassisMake) {
    this.chassisMake = chassisMake;
  }

  public MakeModel chassisModel(String chassisModel) {
    this.chassisModel = chassisModel;
    return this;
  }

   /**
   * ALL
   * @return chassisModel
  **/
  public String getChassisModel() {
    return chassisModel;
  }

  public void setChassisModel(String chassisModel) {
    this.chassisModel = chassisModel;
  }

  public MakeModel bodyMake(String bodyMake) {
    this.bodyMake = bodyMake;
    return this;
  }

   /**
   * ALL
   * @return bodyMake
  **/
  public String getBodyMake() {
    return bodyMake;
  }

  public void setBodyMake(String bodyMake) {
    this.bodyMake = bodyMake;
  }

  public MakeModel bodyModel(String bodyModel) {
    this.bodyModel = bodyModel;
    return this;
  }

   /**
   * ALL
   * @return bodyModel
  **/
  public String getBodyModel() {
    return bodyModel;
  }

  public void setBodyModel(String bodyModel) {
    this.bodyModel = bodyModel;
  }

  public MakeModel modelLiteral(String modelLiteral) {
    this.modelLiteral = modelLiteral;
    return this;
  }

   /**
   * ALL
   * @return modelLiteral
  **/
  public String getModelLiteral() {
    return modelLiteral;
  }

  public void setModelLiteral(String modelLiteral) {
    this.modelLiteral = modelLiteral;
  }

  public MakeModel bodyTypeCode(String bodyTypeCode) {
    this.bodyTypeCode = bodyTypeCode;
    return this;
  }

   /**
   * ALL
   * @return bodyTypeCode
  **/
  public String getBodyTypeCode() {
    return bodyTypeCode;
  }

  public void setBodyTypeCode(String bodyTypeCode) {
    this.bodyTypeCode = bodyTypeCode;
  }

  public MakeModel bodyTypeDescription(String bodyTypeDescription) {
    this.bodyTypeDescription = bodyTypeDescription;
    return this;
  }

   /**
   * ALL
   * @return bodyTypeDescription
  **/
  public String getBodyTypeDescription() {
    return bodyTypeDescription;
  }

  public void setBodyTypeDescription(String bodyTypeDescription) {
    this.bodyTypeDescription = bodyTypeDescription;
  }

  public MakeModel fuelPropulsionSystem(String fuelPropulsionSystem) {
    this.fuelPropulsionSystem = fuelPropulsionSystem;
    return this;
  }

   /**
   * ALL
   * @return fuelPropulsionSystem
  **/
  public String getFuelPropulsionSystem() {
    return fuelPropulsionSystem;
  }

  public void setFuelPropulsionSystem(String fuelPropulsionSystem) {
    this.fuelPropulsionSystem = fuelPropulsionSystem;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MakeModel makeModel = (MakeModel) o;
    return Objects.equals(this.make, makeModel.make) &&
        Objects.equals(this.model, makeModel.model) &&
        Objects.equals(this.chassisMake, makeModel.chassisMake) &&
        Objects.equals(this.chassisModel, makeModel.chassisModel) &&
        Objects.equals(this.bodyMake, makeModel.bodyMake) &&
        Objects.equals(this.bodyModel, makeModel.bodyModel) &&
        Objects.equals(this.modelLiteral, makeModel.modelLiteral) &&
        Objects.equals(this.bodyTypeCode, makeModel.bodyTypeCode) &&
        Objects.equals(this.bodyTypeDescription, makeModel.bodyTypeDescription) &&
        Objects.equals(this.fuelPropulsionSystem, makeModel.fuelPropulsionSystem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(make, model, chassisMake, chassisModel, bodyMake, bodyModel, modelLiteral, bodyTypeCode, bodyTypeDescription, fuelPropulsionSystem);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MakeModel {\n");
    
    sb.append("    make: ").append(toIndentedString(make)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    chassisMake: ").append(toIndentedString(chassisMake)).append("\n");
    sb.append("    chassisModel: ").append(toIndentedString(chassisModel)).append("\n");
    sb.append("    bodyMake: ").append(toIndentedString(bodyMake)).append("\n");
    sb.append("    bodyModel: ").append(toIndentedString(bodyModel)).append("\n");
    sb.append("    modelLiteral: ").append(toIndentedString(modelLiteral)).append("\n");
    sb.append("    bodyTypeCode: ").append(toIndentedString(bodyTypeCode)).append("\n");
    sb.append("    bodyTypeDescription: ").append(toIndentedString(bodyTypeDescription)).append("\n");
    sb.append("    fuelPropulsionSystem: ").append(toIndentedString(fuelPropulsionSystem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
