/*
 * Vehicle Enquiry Service Swagger
 * This is the CVS API for showing details of heavy goods vehicles and their associated test result.
 *
 * OpenAPI spec version: 1.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.enquiry;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * Plate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T17:16:44.237Z[GMT]")
public class Plate {
  @SerializedName("plateSerialNumber")
  private String plateSerialNumber = null;

  @SerializedName("plateIssueDate")
  private String plateIssueDate = null;

  @SerializedName("plateReasonForIssue")
  private String plateReasonForIssue = null;

  @SerializedName("plateIssuer")
  private Integer plateIssuer = null;

  public Plate plateSerialNumber(String plateSerialNumber) {
    this.plateSerialNumber = plateSerialNumber;
    return this;
  }

   /**
   * Get plateSerialNumber
   * @return plateSerialNumber
  **/
  public String getPlateSerialNumber() {
    return plateSerialNumber;
  }

  public void setPlateSerialNumber(String plateSerialNumber) {
    this.plateSerialNumber = plateSerialNumber;
  }

  public Plate plateIssueDate(String plateIssueDate) {
    this.plateIssueDate = plateIssueDate;
    return this;
  }

   /**
   * Get plateIssueDate
   * @return plateIssueDate
  **/
  public String getPlateIssueDate() {
    return plateIssueDate;
  }

  public void setPlateIssueDate(String plateIssueDate) {
    this.plateIssueDate = plateIssueDate;
  }

  public Plate plateReasonForIssue(String plateReasonForIssue) {
    this.plateReasonForIssue = plateReasonForIssue;
    return this;
  }

   /**
   * Get plateReasonForIssue
   * @return plateReasonForIssue
  **/
  public String getPlateReasonForIssue() {
    return plateReasonForIssue;
  }

  public void setPlateReasonForIssue(String plateReasonForIssue) {
    this.plateReasonForIssue = plateReasonForIssue;
  }

  public Plate plateIssuer(Integer plateIssuer) {
    this.plateIssuer = plateIssuer;
    return this;
  }

   /**
   * Get plateIssuer
   * @return plateIssuer
  **/
  public Integer getPlateIssuer() {
    return plateIssuer;
  }

  public void setPlateIssuer(Integer plateIssuer) {
    this.plateIssuer = plateIssuer;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Plate plate = (Plate) o;
    return Objects.equals(this.plateSerialNumber, plate.plateSerialNumber) &&
        Objects.equals(this.plateIssueDate, plate.plateIssueDate) &&
        Objects.equals(this.plateReasonForIssue, plate.plateReasonForIssue) &&
        Objects.equals(this.plateIssuer, plate.plateIssuer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plateSerialNumber, plateIssueDate, plateReasonForIssue, plateIssuer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Plate {\n");
    
    sb.append("    plateSerialNumber: ").append(toIndentedString(plateSerialNumber)).append("\n");
    sb.append("    plateIssueDate: ").append(toIndentedString(plateIssueDate)).append("\n");
    sb.append("    plateReasonForIssue: ").append(toIndentedString(plateReasonForIssue)).append("\n");
    sb.append("    plateIssuer: ").append(toIndentedString(plateIssuer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
