/*
 * Vehicle Enquiry Service Swagger
 * This is the CVS API for showing details of heavy goods vehicles and their associated test result.
 *
 * OpenAPI spec version: 1.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.enquiry;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;


import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * TechnicalRecord
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T17:16:44.237Z[GMT]")
public class TechnicalRecord {
  /**
   * Gets or Sets recordtype
   */
  @JsonAdapter(RecordtypeEnum.Adapter.class)
  public enum RecordtypeEnum {
    CURRENT("current"),
    PROVISONAL("provisonal");

    private String value;

    RecordtypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static RecordtypeEnum fromValue(String text) {
      for (RecordtypeEnum b : RecordtypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<RecordtypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RecordtypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RecordtypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return RecordtypeEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("recordtype")
  private RecordtypeEnum recordtype = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("lastUpdatedAt")
  private String lastUpdatedAt = null;

  @SerializedName("makeModel")
  private MakeModel makeModel = null;

  @SerializedName("functionCode")
  private String functionCode = null;

  @SerializedName("offRoad")
  private Boolean offRoad = null;

  @SerializedName("numberOfWheelsDriven")
  private Integer numberOfWheelsDriven = null;

  @SerializedName("emissionsLimit")
  private String emissionsLimit = null;

  @SerializedName("departmentalVehicleMarker")
  private Boolean departmentalVehicleMarker = null;

  @SerializedName("alterationMarker")
  private Boolean alterationMarker = null;

  @SerializedName("vehicleClass")
  private VehicleClass vehicleClass = null;

  @SerializedName("variantVersionNumber")
  private String variantVersionNumber = null;

  @SerializedName("grossEecWeight")
  private Integer grossEecWeight = null;

  @SerializedName("trainEecWeight")
  private Integer trainEecWeight = null;

  @SerializedName("maxTrainEecWeight")
  private Integer maxTrainEecWeight = null;

  @SerializedName("manufactureYear")
  private String manufactureYear = null;

  @SerializedName("regnDate")
  private String regnDate = null;

  @SerializedName("firstUseDate")
  private String firstUseDate = null;

  @SerializedName("coifDate")
  private String coifDate = null;

  @SerializedName("ntaNumber")
  private String ntaNumber = null;

  @SerializedName("coifSerialNumber")
  private String coifSerialNumber = null;

  @SerializedName("coifCertifierName")
  private String coifCertifierName = null;

  @SerializedName("approvalType")
  private String approvalType = null;

  @SerializedName("approvalTypeNumber")
  private String approvalTypeNumber = null;

  @SerializedName("variantNumber")
  private String variantNumber = null;

  @SerializedName("conversionRefNo")
  private String conversionRefNo = null;

  @SerializedName("seatsLowerDeck")
  private Integer seatsLowerDeck = null;

  @SerializedName("seatsUpperDeck")
  private Integer seatsUpperDeck = null;

  @SerializedName("standingCapacity")
  private Integer standingCapacity = null;

  @SerializedName("speedRestriction")
  private Integer speedRestriction = null;

  @SerializedName("speedLimiterMrk")
  private Boolean speedLimiterMrk = null;

  @SerializedName("tachoExemptMrk")
  private Boolean tachoExemptMrk = null;

  @SerializedName("dispensations")
  private String dispensations = null;

  @SerializedName("remarks")
  private String remarks = null;

  @SerializedName("reasonForCreation")
  private String reasonForCreation = null;

  @SerializedName("statusCode")
  private String statusCode = null;

  @SerializedName("unladenWeight")
  private Integer unladenWeight = null;

  @SerializedName("grossKerbWeight")
  private Integer grossKerbWeight = null;

  @SerializedName("grossLadenWeight")
  private Integer grossLadenWeight = null;

  @SerializedName("grossGbWeight")
  private Integer grossGbWeight = null;

  @SerializedName("grossDesignWeight")
  private Integer grossDesignWeight = null;

  @SerializedName("trainGbWeight")
  private Integer trainGbWeight = null;

  @SerializedName("trainDesignWeight")
  private Integer trainDesignWeight = null;

  @SerializedName("maxTrainGbWeight")
  private Integer maxTrainGbWeight = null;

  @SerializedName("maxTrainDesignWeight")
  private Integer maxTrainDesignWeight = null;

  @SerializedName("maxLoadOnCoupling")
  private Integer maxLoadOnCoupling = null;

  @SerializedName("frameDescription")
  private String frameDescription = null;

  @SerializedName("tyreUseCode")
  private String tyreUseCode = null;

  @SerializedName("roadFriendly")
  private Boolean roadFriendly = null;

  @SerializedName("drawbarCouplingFitted")
  private Boolean drawbarCouplingFitted = null;

  @SerializedName("euroStandard")
  private String euroStandard = null;

  @SerializedName("suspensionType")
  private String suspensionType = null;

  @SerializedName("couplingType")
  private String couplingType = null;

  @SerializedName("length")
  private Integer length = null;

  @SerializedName("height")
  private Integer height = null;

  @SerializedName("width")
  private Integer width = null;

  @SerializedName("frontAxleTo5thWheelMin")
  private Integer frontAxleTo5thWheelMin = null;

  @SerializedName("frontAxleTo5thWheelMax")
  private Integer frontAxleTo5thWheelMax = null;

  @SerializedName("frontAxleTo5thWheelCouplingMin")
  private Integer frontAxleTo5thWheelCouplingMin = null;

  @SerializedName("frontAxleTo5thWheelCouplingMax")
  private Integer frontAxleTo5thWheelCouplingMax = null;

  @SerializedName("frontAxleToRearAxle")
  private Integer frontAxleToRearAxle = null;

  @SerializedName("rearAxleToRearTrl")
  private Integer rearAxleToRearTrl = null;

  @SerializedName("couplingCentreToRearAxleMin")
  private Integer couplingCentreToRearAxleMin = null;

  @SerializedName("couplingCentreToRearAxleMax")
  private Integer couplingCentreToRearAxleMax = null;

  @SerializedName("couplingCentreToRearTrlMin")
  private Integer couplingCentreToRearTrlMin = null;

  @SerializedName("couplingCentreToRearTrlMax")
  private Integer couplingCentreToRearTrlMax = null;

  @SerializedName("centreOfRearmostAxleToRearOfTrl")
  private Integer centreOfRearmostAxleToRearOfTrl = null;

  @SerializedName("notes")
  private String notes = null;

  @SerializedName("purchaserNotes")
  private String purchaserNotes = null;

  @SerializedName("manufacturerNotes")
  private String manufacturerNotes = null;

  @SerializedName("noOfAxles")
  private Integer noOfAxles = null;

  @SerializedName("brakeCode")
  private String brakeCode = null;

  @SerializedName("numberOfSeatbelts")
  private String numberOfSeatbelts = null;

  @SerializedName("seatbeltInstallationApprovalDate")
  private String seatbeltInstallationApprovalDate = null;

  @SerializedName("psvBrakes")
  private List<PSVBrakes> psvBrakes = null;

  @SerializedName("axles")
  private List<Axles> axles = null;

  @SerializedName("axlespacing")
  private List<AxleSpacing> axlespacing = null;

  @SerializedName("plates")
  private List<Plate> plates = null;

  @SerializedName("dtpNumber")
  private String dtpNumber = null;

  @SerializedName("loadSensingValve")
  private Boolean loadSensingValve = null;

  @SerializedName("antilockBrakingSystem")
  private Boolean antilockBrakingSystem = null;

  public TechnicalRecord recordtype(RecordtypeEnum recordtype) {
    this.recordtype = recordtype;
    return this;
  }

   /**
   * Get recordtype
   * @return recordtype
  **/
  public RecordtypeEnum getRecordtype() {
    return recordtype;
  }

  public void setRecordtype(RecordtypeEnum recordtype) {
    this.recordtype = recordtype;
  }

  public TechnicalRecord createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ALL
   * @return createdAt
  **/
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public TechnicalRecord lastUpdatedAt(String lastUpdatedAt) {
    this.lastUpdatedAt = lastUpdatedAt;
    return this;
  }

   /**
   * ALL
   * @return lastUpdatedAt
  **/
  public String getLastUpdatedAt() {
    return lastUpdatedAt;
  }

  public void setLastUpdatedAt(String lastUpdatedAt) {
    this.lastUpdatedAt = lastUpdatedAt;
  }

  public TechnicalRecord makeModel(MakeModel makeModel) {
    this.makeModel = makeModel;
    return this;
  }

   /**
   * Get makeModel
   * @return makeModel
  **/
  public MakeModel getMakeModel() {
    return makeModel;
  }

  public void setMakeModel(MakeModel makeModel) {
    this.makeModel = makeModel;
  }

  public TechnicalRecord functionCode(String functionCode) {
    this.functionCode = functionCode;
    return this;
  }

   /**
   * ALL
   * @return functionCode
  **/
  public String getFunctionCode() {
    return functionCode;
  }

  public void setFunctionCode(String functionCode) {
    this.functionCode = functionCode;
  }

  public TechnicalRecord offRoad(Boolean offRoad) {
    this.offRoad = offRoad;
    return this;
  }

   /**
   * HGV
   * @return offRoad
  **/
  public Boolean isOffRoad() {
    return offRoad;
  }

  public void setOffRoad(Boolean offRoad) {
    this.offRoad = offRoad;
  }

  public TechnicalRecord numberOfWheelsDriven(Integer numberOfWheelsDriven) {
    this.numberOfWheelsDriven = numberOfWheelsDriven;
    return this;
  }

   /**
   * HGV/PSV
   * @return numberOfWheelsDriven
  **/
  public Integer getNumberOfWheelsDriven() {
    return numberOfWheelsDriven;
  }

  public void setNumberOfWheelsDriven(Integer numberOfWheelsDriven) {
    this.numberOfWheelsDriven = numberOfWheelsDriven;
  }

  public TechnicalRecord emissionsLimit(String emissionsLimit) {
    this.emissionsLimit = emissionsLimit;
    return this;
  }

   /**
   * HGV/PSV
   * @return emissionsLimit
  **/
  public String getEmissionsLimit() {
    return emissionsLimit;
  }

  public void setEmissionsLimit(String emissionsLimit) {
    this.emissionsLimit = emissionsLimit;
  }

  public TechnicalRecord departmentalVehicleMarker(Boolean departmentalVehicleMarker) {
    this.departmentalVehicleMarker = departmentalVehicleMarker;
    return this;
  }

   /**
   * ALL
   * @return departmentalVehicleMarker
  **/
  public Boolean isDepartmentalVehicleMarker() {
    return departmentalVehicleMarker;
  }

  public void setDepartmentalVehicleMarker(Boolean departmentalVehicleMarker) {
    this.departmentalVehicleMarker = departmentalVehicleMarker;
  }

  public TechnicalRecord alterationMarker(Boolean alterationMarker) {
    this.alterationMarker = alterationMarker;
    return this;
  }

   /**
   * ALL
   * @return alterationMarker
  **/
  public Boolean isAlterationMarker() {
    return alterationMarker;
  }

  public void setAlterationMarker(Boolean alterationMarker) {
    this.alterationMarker = alterationMarker;
  }

  public TechnicalRecord vehicleClass(VehicleClass vehicleClass) {
    this.vehicleClass = vehicleClass;
    return this;
  }

   /**
   * Get vehicleClass
   * @return vehicleClass
  **/
  public VehicleClass getVehicleClass() {
    return vehicleClass;
  }

  public void setVehicleClass(VehicleClass vehicleClass) {
    this.vehicleClass = vehicleClass;
  }

  public TechnicalRecord variantVersionNumber(String variantVersionNumber) {
    this.variantVersionNumber = variantVersionNumber;
    return this;
  }

   /**
   * ALL
   * @return variantVersionNumber
  **/
  public String getVariantVersionNumber() {
    return variantVersionNumber;
  }

  public void setVariantVersionNumber(String variantVersionNumber) {
    this.variantVersionNumber = variantVersionNumber;
  }

  public TechnicalRecord grossEecWeight(Integer grossEecWeight) {
    this.grossEecWeight = grossEecWeight;
    return this;
  }

   /**
   * HGV/TRL
   * @return grossEecWeight
  **/
  public Integer getGrossEecWeight() {
    return grossEecWeight;
  }

  public void setGrossEecWeight(Integer grossEecWeight) {
    this.grossEecWeight = grossEecWeight;
  }

  public TechnicalRecord trainEecWeight(Integer trainEecWeight) {
    this.trainEecWeight = trainEecWeight;
    return this;
  }

   /**
   * HGV
   * @return trainEecWeight
  **/
  public Integer getTrainEecWeight() {
    return trainEecWeight;
  }

  public void setTrainEecWeight(Integer trainEecWeight) {
    this.trainEecWeight = trainEecWeight;
  }

  public TechnicalRecord maxTrainEecWeight(Integer maxTrainEecWeight) {
    this.maxTrainEecWeight = maxTrainEecWeight;
    return this;
  }

   /**
   * HGV
   * @return maxTrainEecWeight
  **/
  public Integer getMaxTrainEecWeight() {
    return maxTrainEecWeight;
  }

  public void setMaxTrainEecWeight(Integer maxTrainEecWeight) {
    this.maxTrainEecWeight = maxTrainEecWeight;
  }

  public TechnicalRecord manufactureYear(String manufactureYear) {
    this.manufactureYear = manufactureYear;
    return this;
  }

   /**
   * ALL
   * @return manufactureYear
  **/
  public String getManufactureYear() {
    return manufactureYear;
  }

  public void setManufactureYear(String manufactureYear) {
    this.manufactureYear = manufactureYear;
  }

  public TechnicalRecord regnDate(String regnDate) {
    this.regnDate = regnDate;
    return this;
  }

   /**
   * ALL
   * @return regnDate
  **/
  public String getRegnDate() {
    return regnDate;
  }

  public void setRegnDate(String regnDate) {
    this.regnDate = regnDate;
  }

  public TechnicalRecord firstUseDate(String firstUseDate) {
    this.firstUseDate = firstUseDate;
    return this;
  }

   /**
   * ALL
   * @return firstUseDate
  **/
  public String getFirstUseDate() {
    return firstUseDate;
  }

  public void setFirstUseDate(String firstUseDate) {
    this.firstUseDate = firstUseDate;
  }

  public TechnicalRecord coifDate(String coifDate) {
    this.coifDate = coifDate;
    return this;
  }

   /**
   * PSV
   * @return coifDate
  **/
  public String getCoifDate() {
    return coifDate;
  }

  public void setCoifDate(String coifDate) {
    this.coifDate = coifDate;
  }

  public TechnicalRecord ntaNumber(String ntaNumber) {
    this.ntaNumber = ntaNumber;
    return this;
  }

   /**
   * ALL
   * @return ntaNumber
  **/
  public String getNtaNumber() {
    return ntaNumber;
  }

  public void setNtaNumber(String ntaNumber) {
    this.ntaNumber = ntaNumber;
  }

  public TechnicalRecord coifSerialNumber(String coifSerialNumber) {
    this.coifSerialNumber = coifSerialNumber;
    return this;
  }

   /**
   * PSV
   * @return coifSerialNumber
  **/
  public String getCoifSerialNumber() {
    return coifSerialNumber;
  }

  public void setCoifSerialNumber(String coifSerialNumber) {
    this.coifSerialNumber = coifSerialNumber;
  }

  public TechnicalRecord coifCertifierName(String coifCertifierName) {
    this.coifCertifierName = coifCertifierName;
    return this;
  }

   /**
   * PSV
   * @return coifCertifierName
  **/
  public String getCoifCertifierName() {
    return coifCertifierName;
  }

  public void setCoifCertifierName(String coifCertifierName) {
    this.coifCertifierName = coifCertifierName;
  }

  public TechnicalRecord approvalType(String approvalType) {
    this.approvalType = approvalType;
    return this;
  }

   /**
   * ALL
   * @return approvalType
  **/
  public String getApprovalType() {
    return approvalType;
  }

  public void setApprovalType(String approvalType) {
    this.approvalType = approvalType;
  }

  public TechnicalRecord approvalTypeNumber(String approvalTypeNumber) {
    this.approvalTypeNumber = approvalTypeNumber;
    return this;
  }

   /**
   * ALL
   * @return approvalTypeNumber
  **/
  public String getApprovalTypeNumber() {
    return approvalTypeNumber;
  }

  public void setApprovalTypeNumber(String approvalTypeNumber) {
    this.approvalTypeNumber = approvalTypeNumber;
  }

  public TechnicalRecord variantNumber(String variantNumber) {
    this.variantNumber = variantNumber;
    return this;
  }

   /**
   * ALL
   * @return variantNumber
  **/
  public String getVariantNumber() {
    return variantNumber;
  }

  public void setVariantNumber(String variantNumber) {
    this.variantNumber = variantNumber;
  }

  public TechnicalRecord conversionRefNo(String conversionRefNo) {
    this.conversionRefNo = conversionRefNo;
    return this;
  }

   /**
   * ALL
   * @return conversionRefNo
  **/
  public String getConversionRefNo() {
    return conversionRefNo;
  }

  public void setConversionRefNo(String conversionRefNo) {
    this.conversionRefNo = conversionRefNo;
  }

  public TechnicalRecord seatsLowerDeck(Integer seatsLowerDeck) {
    this.seatsLowerDeck = seatsLowerDeck;
    return this;
  }

   /**
   * PSV
   * @return seatsLowerDeck
  **/
  public Integer getSeatsLowerDeck() {
    return seatsLowerDeck;
  }

  public void setSeatsLowerDeck(Integer seatsLowerDeck) {
    this.seatsLowerDeck = seatsLowerDeck;
  }

  public TechnicalRecord seatsUpperDeck(Integer seatsUpperDeck) {
    this.seatsUpperDeck = seatsUpperDeck;
    return this;
  }

   /**
   * PSV
   * @return seatsUpperDeck
  **/
  public Integer getSeatsUpperDeck() {
    return seatsUpperDeck;
  }

  public void setSeatsUpperDeck(Integer seatsUpperDeck) {
    this.seatsUpperDeck = seatsUpperDeck;
  }

  public TechnicalRecord standingCapacity(Integer standingCapacity) {
    this.standingCapacity = standingCapacity;
    return this;
  }

   /**
   * PSV
   * @return standingCapacity
  **/
  public Integer getStandingCapacity() {
    return standingCapacity;
  }

  public void setStandingCapacity(Integer standingCapacity) {
    this.standingCapacity = standingCapacity;
  }

  public TechnicalRecord speedRestriction(Integer speedRestriction) {
    this.speedRestriction = speedRestriction;
    return this;
  }

   /**
   * PSV
   * @return speedRestriction
  **/
  public Integer getSpeedRestriction() {
    return speedRestriction;
  }

  public void setSpeedRestriction(Integer speedRestriction) {
    this.speedRestriction = speedRestriction;
  }

  public TechnicalRecord speedLimiterMrk(Boolean speedLimiterMrk) {
    this.speedLimiterMrk = speedLimiterMrk;
    return this;
  }

   /**
   * HGV/PSV
   * @return speedLimiterMrk
  **/
  public Boolean isSpeedLimiterMrk() {
    return speedLimiterMrk;
  }

  public void setSpeedLimiterMrk(Boolean speedLimiterMrk) {
    this.speedLimiterMrk = speedLimiterMrk;
  }

  public TechnicalRecord tachoExemptMrk(Boolean tachoExemptMrk) {
    this.tachoExemptMrk = tachoExemptMrk;
    return this;
  }

   /**
   * HGV/PSV
   * @return tachoExemptMrk
  **/
  public Boolean isTachoExemptMrk() {
    return tachoExemptMrk;
  }

  public void setTachoExemptMrk(Boolean tachoExemptMrk) {
    this.tachoExemptMrk = tachoExemptMrk;
  }

  public TechnicalRecord dispensations(String dispensations) {
    this.dispensations = dispensations;
    return this;
  }

   /**
   * PSV
   * @return dispensations
  **/
  public String getDispensations() {
    return dispensations;
  }

  public void setDispensations(String dispensations) {
    this.dispensations = dispensations;
  }

  public TechnicalRecord remarks(String remarks) {
    this.remarks = remarks;
    return this;
  }

   /**
   * PSV
   * @return remarks
  **/
  public String getRemarks() {
    return remarks;
  }

  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  public TechnicalRecord reasonForCreation(String reasonForCreation) {
    this.reasonForCreation = reasonForCreation;
    return this;
  }

   /**
   * ALL
   * @return reasonForCreation
  **/
  public String getReasonForCreation() {
    return reasonForCreation;
  }

  public void setReasonForCreation(String reasonForCreation) {
    this.reasonForCreation = reasonForCreation;
  }

  public TechnicalRecord statusCode(String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * ALL
   * @return statusCode
  **/
  public String getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(String statusCode) {
    this.statusCode = statusCode;
  }

  public TechnicalRecord unladenWeight(Integer unladenWeight) {
    this.unladenWeight = unladenWeight;
    return this;
  }

   /**
   * PSV
   * @return unladenWeight
  **/
  public Integer getUnladenWeight() {
    return unladenWeight;
  }

  public void setUnladenWeight(Integer unladenWeight) {
    this.unladenWeight = unladenWeight;
  }

  public TechnicalRecord grossKerbWeight(Integer grossKerbWeight) {
    this.grossKerbWeight = grossKerbWeight;
    return this;
  }

   /**
   * PSV
   * @return grossKerbWeight
  **/
  public Integer getGrossKerbWeight() {
    return grossKerbWeight;
  }

  public void setGrossKerbWeight(Integer grossKerbWeight) {
    this.grossKerbWeight = grossKerbWeight;
  }

  public TechnicalRecord grossLadenWeight(Integer grossLadenWeight) {
    this.grossLadenWeight = grossLadenWeight;
    return this;
  }

   /**
   * PSV
   * @return grossLadenWeight
  **/
  public Integer getGrossLadenWeight() {
    return grossLadenWeight;
  }

  public void setGrossLadenWeight(Integer grossLadenWeight) {
    this.grossLadenWeight = grossLadenWeight;
  }

  public TechnicalRecord grossGbWeight(Integer grossGbWeight) {
    this.grossGbWeight = grossGbWeight;
    return this;
  }

   /**
   * ALL
   * @return grossGbWeight
  **/
  public Integer getGrossGbWeight() {
    return grossGbWeight;
  }

  public void setGrossGbWeight(Integer grossGbWeight) {
    this.grossGbWeight = grossGbWeight;
  }

  public TechnicalRecord grossDesignWeight(Integer grossDesignWeight) {
    this.grossDesignWeight = grossDesignWeight;
    return this;
  }

   /**
   * ALL
   * @return grossDesignWeight
  **/
  public Integer getGrossDesignWeight() {
    return grossDesignWeight;
  }

  public void setGrossDesignWeight(Integer grossDesignWeight) {
    this.grossDesignWeight = grossDesignWeight;
  }

  public TechnicalRecord trainGbWeight(Integer trainGbWeight) {
    this.trainGbWeight = trainGbWeight;
    return this;
  }

   /**
   * HGV
   * @return trainGbWeight
  **/
  public Integer getTrainGbWeight() {
    return trainGbWeight;
  }

  public void setTrainGbWeight(Integer trainGbWeight) {
    this.trainGbWeight = trainGbWeight;
  }

  public TechnicalRecord trainDesignWeight(Integer trainDesignWeight) {
    this.trainDesignWeight = trainDesignWeight;
    return this;
  }

   /**
   * HGV/PSV
   * @return trainDesignWeight
  **/
  public Integer getTrainDesignWeight() {
    return trainDesignWeight;
  }

  public void setTrainDesignWeight(Integer trainDesignWeight) {
    this.trainDesignWeight = trainDesignWeight;
  }

  public TechnicalRecord maxTrainGbWeight(Integer maxTrainGbWeight) {
    this.maxTrainGbWeight = maxTrainGbWeight;
    return this;
  }

   /**
   * HGV/PSV
   * @return maxTrainGbWeight
  **/
  public Integer getMaxTrainGbWeight() {
    return maxTrainGbWeight;
  }

  public void setMaxTrainGbWeight(Integer maxTrainGbWeight) {
    this.maxTrainGbWeight = maxTrainGbWeight;
  }

  public TechnicalRecord maxTrainDesignWeight(Integer maxTrainDesignWeight) {
    this.maxTrainDesignWeight = maxTrainDesignWeight;
    return this;
  }

   /**
   * HGV
   * @return maxTrainDesignWeight
  **/
  public Integer getMaxTrainDesignWeight() {
    return maxTrainDesignWeight;
  }

  public void setMaxTrainDesignWeight(Integer maxTrainDesignWeight) {
    this.maxTrainDesignWeight = maxTrainDesignWeight;
  }

  public TechnicalRecord maxLoadOnCoupling(Integer maxLoadOnCoupling) {
    this.maxLoadOnCoupling = maxLoadOnCoupling;
    return this;
  }

   /**
   * TRL
   * @return maxLoadOnCoupling
  **/
  public Integer getMaxLoadOnCoupling() {
    return maxLoadOnCoupling;
  }

  public void setMaxLoadOnCoupling(Integer maxLoadOnCoupling) {
    this.maxLoadOnCoupling = maxLoadOnCoupling;
  }

  public TechnicalRecord frameDescription(String frameDescription) {
    this.frameDescription = frameDescription;
    return this;
  }

   /**
   * UNK
   * @return frameDescription
  **/
  public String getFrameDescription() {
    return frameDescription;
  }

  public void setFrameDescription(String frameDescription) {
    this.frameDescription = frameDescription;
  }

  public TechnicalRecord tyreUseCode(String tyreUseCode) {
    this.tyreUseCode = tyreUseCode;
    return this;
  }

   /**
   * HGV/TRL
   * @return tyreUseCode
  **/
  public String getTyreUseCode() {
    return tyreUseCode;
  }

  public void setTyreUseCode(String tyreUseCode) {
    this.tyreUseCode = tyreUseCode;
  }

  public TechnicalRecord roadFriendly(Boolean roadFriendly) {
    this.roadFriendly = roadFriendly;
    return this;
  }

   /**
   * HGV/TRL
   * @return roadFriendly
  **/
  public Boolean isRoadFriendly() {
    return roadFriendly;
  }

  public void setRoadFriendly(Boolean roadFriendly) {
    this.roadFriendly = roadFriendly;
  }

  public TechnicalRecord drawbarCouplingFitted(Boolean drawbarCouplingFitted) {
    this.drawbarCouplingFitted = drawbarCouplingFitted;
    return this;
  }

   /**
   * HGV
   * @return drawbarCouplingFitted
  **/
  public Boolean isDrawbarCouplingFitted() {
    return drawbarCouplingFitted;
  }

  public void setDrawbarCouplingFitted(Boolean drawbarCouplingFitted) {
    this.drawbarCouplingFitted = drawbarCouplingFitted;
  }

  public TechnicalRecord euroStandard(String euroStandard) {
    this.euroStandard = euroStandard;
    return this;
  }

   /**
   * HGV/PSV
   * @return euroStandard
  **/
  public String getEuroStandard() {
    return euroStandard;
  }

  public void setEuroStandard(String euroStandard) {
    this.euroStandard = euroStandard;
  }

  public TechnicalRecord suspensionType(String suspensionType) {
    this.suspensionType = suspensionType;
    return this;
  }

   /**
   * TRL
   * @return suspensionType
  **/
  public String getSuspensionType() {
    return suspensionType;
  }

  public void setSuspensionType(String suspensionType) {
    this.suspensionType = suspensionType;
  }

  public TechnicalRecord couplingType(String couplingType) {
    this.couplingType = couplingType;
    return this;
  }

   /**
   * TRL
   * @return couplingType
  **/
  public String getCouplingType() {
    return couplingType;
  }

  public void setCouplingType(String couplingType) {
    this.couplingType = couplingType;
  }

  public TechnicalRecord length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * ALL
   * @return length
  **/
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public TechnicalRecord height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * PSV
   * @return height
  **/
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public TechnicalRecord width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * ALL
   * @return width
  **/
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }

  public TechnicalRecord frontAxleTo5thWheelMin(Integer frontAxleTo5thWheelMin) {
    this.frontAxleTo5thWheelMin = frontAxleTo5thWheelMin;
    return this;
  }

   /**
   * HGV
   * @return frontAxleTo5thWheelMin
  **/
  public Integer getFrontAxleTo5thWheelMin() {
    return frontAxleTo5thWheelMin;
  }

  public void setFrontAxleTo5thWheelMin(Integer frontAxleTo5thWheelMin) {
    this.frontAxleTo5thWheelMin = frontAxleTo5thWheelMin;
  }

  public TechnicalRecord frontAxleTo5thWheelMax(Integer frontAxleTo5thWheelMax) {
    this.frontAxleTo5thWheelMax = frontAxleTo5thWheelMax;
    return this;
  }

   /**
   * HGV
   * @return frontAxleTo5thWheelMax
  **/
  public Integer getFrontAxleTo5thWheelMax() {
    return frontAxleTo5thWheelMax;
  }

  public void setFrontAxleTo5thWheelMax(Integer frontAxleTo5thWheelMax) {
    this.frontAxleTo5thWheelMax = frontAxleTo5thWheelMax;
  }

  public TechnicalRecord frontAxleTo5thWheelCouplingMin(Integer frontAxleTo5thWheelCouplingMin) {
    this.frontAxleTo5thWheelCouplingMin = frontAxleTo5thWheelCouplingMin;
    return this;
  }

   /**
   * HGV
   * @return frontAxleTo5thWheelCouplingMin
  **/
  public Integer getFrontAxleTo5thWheelCouplingMin() {
    return frontAxleTo5thWheelCouplingMin;
  }

  public void setFrontAxleTo5thWheelCouplingMin(Integer frontAxleTo5thWheelCouplingMin) {
    this.frontAxleTo5thWheelCouplingMin = frontAxleTo5thWheelCouplingMin;
  }

  public TechnicalRecord frontAxleTo5thWheelCouplingMax(Integer frontAxleTo5thWheelCouplingMax) {
    this.frontAxleTo5thWheelCouplingMax = frontAxleTo5thWheelCouplingMax;
    return this;
  }

   /**
   * HGV
   * @return frontAxleTo5thWheelCouplingMax
  **/
  public Integer getFrontAxleTo5thWheelCouplingMax() {
    return frontAxleTo5thWheelCouplingMax;
  }

  public void setFrontAxleTo5thWheelCouplingMax(Integer frontAxleTo5thWheelCouplingMax) {
    this.frontAxleTo5thWheelCouplingMax = frontAxleTo5thWheelCouplingMax;
  }

  public TechnicalRecord frontAxleToRearAxle(Integer frontAxleToRearAxle) {
    this.frontAxleToRearAxle = frontAxleToRearAxle;
    return this;
  }

   /**
   * ALL
   * @return frontAxleToRearAxle
  **/
  public Integer getFrontAxleToRearAxle() {
    return frontAxleToRearAxle;
  }

  public void setFrontAxleToRearAxle(Integer frontAxleToRearAxle) {
    this.frontAxleToRearAxle = frontAxleToRearAxle;
  }

  public TechnicalRecord rearAxleToRearTrl(Integer rearAxleToRearTrl) {
    this.rearAxleToRearTrl = rearAxleToRearTrl;
    return this;
  }

   /**
   * TRL
   * @return rearAxleToRearTrl
  **/
  public Integer getRearAxleToRearTrl() {
    return rearAxleToRearTrl;
  }

  public void setRearAxleToRearTrl(Integer rearAxleToRearTrl) {
    this.rearAxleToRearTrl = rearAxleToRearTrl;
  }

  public TechnicalRecord couplingCentreToRearAxleMin(Integer couplingCentreToRearAxleMin) {
    this.couplingCentreToRearAxleMin = couplingCentreToRearAxleMin;
    return this;
  }

   /**
   * TRL
   * @return couplingCentreToRearAxleMin
  **/
  public Integer getCouplingCentreToRearAxleMin() {
    return couplingCentreToRearAxleMin;
  }

  public void setCouplingCentreToRearAxleMin(Integer couplingCentreToRearAxleMin) {
    this.couplingCentreToRearAxleMin = couplingCentreToRearAxleMin;
  }

  public TechnicalRecord couplingCentreToRearAxleMax(Integer couplingCentreToRearAxleMax) {
    this.couplingCentreToRearAxleMax = couplingCentreToRearAxleMax;
    return this;
  }

   /**
   * TRL
   * @return couplingCentreToRearAxleMax
  **/
  public Integer getCouplingCentreToRearAxleMax() {
    return couplingCentreToRearAxleMax;
  }

  public void setCouplingCentreToRearAxleMax(Integer couplingCentreToRearAxleMax) {
    this.couplingCentreToRearAxleMax = couplingCentreToRearAxleMax;
  }

  public TechnicalRecord couplingCentreToRearTrlMin(Integer couplingCentreToRearTrlMin) {
    this.couplingCentreToRearTrlMin = couplingCentreToRearTrlMin;
    return this;
  }

   /**
   * TRL
   * @return couplingCentreToRearTrlMin
  **/
  public Integer getCouplingCentreToRearTrlMin() {
    return couplingCentreToRearTrlMin;
  }

  public void setCouplingCentreToRearTrlMin(Integer couplingCentreToRearTrlMin) {
    this.couplingCentreToRearTrlMin = couplingCentreToRearTrlMin;
  }

  public TechnicalRecord couplingCentreToRearTrlMax(Integer couplingCentreToRearTrlMax) {
    this.couplingCentreToRearTrlMax = couplingCentreToRearTrlMax;
    return this;
  }

   /**
   * TRL
   * @return couplingCentreToRearTrlMax
  **/
  public Integer getCouplingCentreToRearTrlMax() {
    return couplingCentreToRearTrlMax;
  }

  public void setCouplingCentreToRearTrlMax(Integer couplingCentreToRearTrlMax) {
    this.couplingCentreToRearTrlMax = couplingCentreToRearTrlMax;
  }

  public TechnicalRecord centreOfRearmostAxleToRearOfTrl(Integer centreOfRearmostAxleToRearOfTrl) {
    this.centreOfRearmostAxleToRearOfTrl = centreOfRearmostAxleToRearOfTrl;
    return this;
  }

   /**
   * TRL
   * @return centreOfRearmostAxleToRearOfTrl
  **/
  public Integer getCentreOfRearmostAxleToRearOfTrl() {
    return centreOfRearmostAxleToRearOfTrl;
  }

  public void setCentreOfRearmostAxleToRearOfTrl(Integer centreOfRearmostAxleToRearOfTrl) {
    this.centreOfRearmostAxleToRearOfTrl = centreOfRearmostAxleToRearOfTrl;
  }

  public TechnicalRecord notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * HGV/TRL
   * @return notes
  **/
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public TechnicalRecord purchaserNotes(String purchaserNotes) {
    this.purchaserNotes = purchaserNotes;
    return this;
  }

   /**
   * HGV/TRL
   * @return purchaserNotes
  **/
  public String getPurchaserNotes() {
    return purchaserNotes;
  }

  public void setPurchaserNotes(String purchaserNotes) {
    this.purchaserNotes = purchaserNotes;
  }

  public TechnicalRecord manufacturerNotes(String manufacturerNotes) {
    this.manufacturerNotes = manufacturerNotes;
    return this;
  }

   /**
   * HGV/TRL
   * @return manufacturerNotes
  **/
  public String getManufacturerNotes() {
    return manufacturerNotes;
  }

  public void setManufacturerNotes(String manufacturerNotes) {
    this.manufacturerNotes = manufacturerNotes;
  }

  public TechnicalRecord noOfAxles(Integer noOfAxles) {
    this.noOfAxles = noOfAxles;
    return this;
  }

   /**
   * ALL
   * @return noOfAxles
  **/
  public Integer getNoOfAxles() {
    return noOfAxles;
  }

  public void setNoOfAxles(Integer noOfAxles) {
    this.noOfAxles = noOfAxles;
  }

  public TechnicalRecord brakeCode(String brakeCode) {
    this.brakeCode = brakeCode;
    return this;
  }

   /**
   * PSV
   * @return brakeCode
  **/
  public String getBrakeCode() {
    return brakeCode;
  }

  public void setBrakeCode(String brakeCode) {
    this.brakeCode = brakeCode;
  }

  public TechnicalRecord numberOfSeatbelts(String numberOfSeatbelts) {
    this.numberOfSeatbelts = numberOfSeatbelts;
    return this;
  }

   /**
   * PSV
   * @return numberOfSeatbelts
  **/
  public String getNumberOfSeatbelts() {
    return numberOfSeatbelts;
  }

  public void setNumberOfSeatbelts(String numberOfSeatbelts) {
    this.numberOfSeatbelts = numberOfSeatbelts;
  }

  public TechnicalRecord seatbeltInstallationApprovalDate(String seatbeltInstallationApprovalDate) {
    this.seatbeltInstallationApprovalDate = seatbeltInstallationApprovalDate;
    return this;
  }

   /**
   * PSV
   * @return seatbeltInstallationApprovalDate
  **/
  public String getSeatbeltInstallationApprovalDate() {
    return seatbeltInstallationApprovalDate;
  }

  public void setSeatbeltInstallationApprovalDate(String seatbeltInstallationApprovalDate) {
    this.seatbeltInstallationApprovalDate = seatbeltInstallationApprovalDate;
  }

  public TechnicalRecord psvBrakes(List<PSVBrakes> psvBrakes) {
    this.psvBrakes = psvBrakes;
    return this;
  }

  public TechnicalRecord addPsvBrakesItem(PSVBrakes psvBrakesItem) {
    if (this.psvBrakes == null) {
      this.psvBrakes = new ArrayList<PSVBrakes>();
    }
    this.psvBrakes.add(psvBrakesItem);
    return this;
  }

   /**
   * Get psvBrakes
   * @return psvBrakes
  **/
  public List<PSVBrakes> getPsvBrakes() {
    return psvBrakes;
  }

  public void setPsvBrakes(List<PSVBrakes> psvBrakes) {
    this.psvBrakes = psvBrakes;
  }

  public TechnicalRecord axles(List<Axles> axles) {
    this.axles = axles;
    return this;
  }

  public TechnicalRecord addAxlesItem(Axles axlesItem) {
    if (this.axles == null) {
      this.axles = new ArrayList<Axles>();
    }
    this.axles.add(axlesItem);
    return this;
  }

   /**
   * Get axles
   * @return axles
  **/
  public List<Axles> getAxles() {
    return axles;
  }

  public void setAxles(List<Axles> axles) {
    this.axles = axles;
  }

  public TechnicalRecord axlespacing(List<AxleSpacing> axlespacing) {
    this.axlespacing = axlespacing;
    return this;
  }

  public TechnicalRecord addAxlespacingItem(AxleSpacing axlespacingItem) {
    if (this.axlespacing == null) {
      this.axlespacing = new ArrayList<AxleSpacing>();
    }
    this.axlespacing.add(axlespacingItem);
    return this;
  }

   /**
   * Get axlespacing
   * @return axlespacing
  **/
  public List<AxleSpacing> getAxlespacing() {
    return axlespacing;
  }

  public void setAxlespacing(List<AxleSpacing> axlespacing) {
    this.axlespacing = axlespacing;
  }

  public TechnicalRecord plates(List<Plate> plates) {
    this.plates = plates;
    return this;
  }

  public TechnicalRecord addPlatesItem(Plate platesItem) {
    if (this.plates == null) {
      this.plates = new ArrayList<Plate>();
    }
    this.plates.add(platesItem);
    return this;
  }

   /**
   * Get plates
   * @return plates
  **/
  public List<Plate> getPlates() {
    return plates;
  }

  public void setPlates(List<Plate> plates) {
    this.plates = plates;
  }

  public TechnicalRecord dtpNumber(String dtpNumber) {
    this.dtpNumber = dtpNumber;
    return this;
  }

   /**
   * Get dtpNumber
   * @return dtpNumber
  **/
  public String getDtpNumber() {
    return dtpNumber;
  }

  public void setDtpNumber(String dtpNumber) {
    this.dtpNumber = dtpNumber;
  }

  public TechnicalRecord loadSensingValve(Boolean loadSensingValve) {
    this.loadSensingValve = loadSensingValve;
    return this;
  }

   /**
   * Get loadSensingValve
   * @return loadSensingValve
  **/
  public Boolean isLoadSensingValve() {
    return loadSensingValve;
  }

  public void setLoadSensingValve(Boolean loadSensingValve) {
    this.loadSensingValve = loadSensingValve;
  }

  public TechnicalRecord antilockBrakingSystem(Boolean antilockBrakingSystem) {
    this.antilockBrakingSystem = antilockBrakingSystem;
    return this;
  }

   /**
   * Get antilockBrakingSystem
   * @return antilockBrakingSystem
  **/
  public Boolean isAntilockBrakingSystem() {
    return antilockBrakingSystem;
  }

  public void setAntilockBrakingSystem(Boolean antilockBrakingSystem) {
    this.antilockBrakingSystem = antilockBrakingSystem;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TechnicalRecord technicalRecord = (TechnicalRecord) o;
    return Objects.equals(this.recordtype, technicalRecord.recordtype) &&
        Objects.equals(this.createdAt, technicalRecord.createdAt) &&
        Objects.equals(this.lastUpdatedAt, technicalRecord.lastUpdatedAt) &&
        Objects.equals(this.makeModel, technicalRecord.makeModel) &&
        Objects.equals(this.functionCode, technicalRecord.functionCode) &&
        Objects.equals(this.offRoad, technicalRecord.offRoad) &&
        Objects.equals(this.numberOfWheelsDriven, technicalRecord.numberOfWheelsDriven) &&
        Objects.equals(this.emissionsLimit, technicalRecord.emissionsLimit) &&
        Objects.equals(this.departmentalVehicleMarker, technicalRecord.departmentalVehicleMarker) &&
        Objects.equals(this.alterationMarker, technicalRecord.alterationMarker) &&
        Objects.equals(this.vehicleClass, technicalRecord.vehicleClass) &&
        Objects.equals(this.variantVersionNumber, technicalRecord.variantVersionNumber) &&
        Objects.equals(this.grossEecWeight, technicalRecord.grossEecWeight) &&
        Objects.equals(this.trainEecWeight, technicalRecord.trainEecWeight) &&
        Objects.equals(this.maxTrainEecWeight, technicalRecord.maxTrainEecWeight) &&
        Objects.equals(this.manufactureYear, technicalRecord.manufactureYear) &&
        Objects.equals(this.regnDate, technicalRecord.regnDate) &&
        Objects.equals(this.firstUseDate, technicalRecord.firstUseDate) &&
        Objects.equals(this.coifDate, technicalRecord.coifDate) &&
        Objects.equals(this.ntaNumber, technicalRecord.ntaNumber) &&
        Objects.equals(this.coifSerialNumber, technicalRecord.coifSerialNumber) &&
        Objects.equals(this.coifCertifierName, technicalRecord.coifCertifierName) &&
        Objects.equals(this.approvalType, technicalRecord.approvalType) &&
        Objects.equals(this.approvalTypeNumber, technicalRecord.approvalTypeNumber) &&
        Objects.equals(this.variantNumber, technicalRecord.variantNumber) &&
        Objects.equals(this.conversionRefNo, technicalRecord.conversionRefNo) &&
        Objects.equals(this.seatsLowerDeck, technicalRecord.seatsLowerDeck) &&
        Objects.equals(this.seatsUpperDeck, technicalRecord.seatsUpperDeck) &&
        Objects.equals(this.standingCapacity, technicalRecord.standingCapacity) &&
        Objects.equals(this.speedRestriction, technicalRecord.speedRestriction) &&
        Objects.equals(this.speedLimiterMrk, technicalRecord.speedLimiterMrk) &&
        Objects.equals(this.tachoExemptMrk, technicalRecord.tachoExemptMrk) &&
        Objects.equals(this.dispensations, technicalRecord.dispensations) &&
        Objects.equals(this.remarks, technicalRecord.remarks) &&
        Objects.equals(this.reasonForCreation, technicalRecord.reasonForCreation) &&
        Objects.equals(this.statusCode, technicalRecord.statusCode) &&
        Objects.equals(this.unladenWeight, technicalRecord.unladenWeight) &&
        Objects.equals(this.grossKerbWeight, technicalRecord.grossKerbWeight) &&
        Objects.equals(this.grossLadenWeight, technicalRecord.grossLadenWeight) &&
        Objects.equals(this.grossGbWeight, technicalRecord.grossGbWeight) &&
        Objects.equals(this.grossDesignWeight, technicalRecord.grossDesignWeight) &&
        Objects.equals(this.trainGbWeight, technicalRecord.trainGbWeight) &&
        Objects.equals(this.trainDesignWeight, technicalRecord.trainDesignWeight) &&
        Objects.equals(this.maxTrainGbWeight, technicalRecord.maxTrainGbWeight) &&
        Objects.equals(this.maxTrainDesignWeight, technicalRecord.maxTrainDesignWeight) &&
        Objects.equals(this.maxLoadOnCoupling, technicalRecord.maxLoadOnCoupling) &&
        Objects.equals(this.frameDescription, technicalRecord.frameDescription) &&
        Objects.equals(this.tyreUseCode, technicalRecord.tyreUseCode) &&
        Objects.equals(this.roadFriendly, technicalRecord.roadFriendly) &&
        Objects.equals(this.drawbarCouplingFitted, technicalRecord.drawbarCouplingFitted) &&
        Objects.equals(this.euroStandard, technicalRecord.euroStandard) &&
        Objects.equals(this.suspensionType, technicalRecord.suspensionType) &&
        Objects.equals(this.couplingType, technicalRecord.couplingType) &&
        Objects.equals(this.length, technicalRecord.length) &&
        Objects.equals(this.height, technicalRecord.height) &&
        Objects.equals(this.width, technicalRecord.width) &&
        Objects.equals(this.frontAxleTo5thWheelMin, technicalRecord.frontAxleTo5thWheelMin) &&
        Objects.equals(this.frontAxleTo5thWheelMax, technicalRecord.frontAxleTo5thWheelMax) &&
        Objects.equals(this.frontAxleTo5thWheelCouplingMin, technicalRecord.frontAxleTo5thWheelCouplingMin) &&
        Objects.equals(this.frontAxleTo5thWheelCouplingMax, technicalRecord.frontAxleTo5thWheelCouplingMax) &&
        Objects.equals(this.frontAxleToRearAxle, technicalRecord.frontAxleToRearAxle) &&
        Objects.equals(this.rearAxleToRearTrl, technicalRecord.rearAxleToRearTrl) &&
        Objects.equals(this.couplingCentreToRearAxleMin, technicalRecord.couplingCentreToRearAxleMin) &&
        Objects.equals(this.couplingCentreToRearAxleMax, technicalRecord.couplingCentreToRearAxleMax) &&
        Objects.equals(this.couplingCentreToRearTrlMin, technicalRecord.couplingCentreToRearTrlMin) &&
        Objects.equals(this.couplingCentreToRearTrlMax, technicalRecord.couplingCentreToRearTrlMax) &&
        Objects.equals(this.centreOfRearmostAxleToRearOfTrl, technicalRecord.centreOfRearmostAxleToRearOfTrl) &&
        Objects.equals(this.notes, technicalRecord.notes) &&
        Objects.equals(this.purchaserNotes, technicalRecord.purchaserNotes) &&
        Objects.equals(this.manufacturerNotes, technicalRecord.manufacturerNotes) &&
        Objects.equals(this.noOfAxles, technicalRecord.noOfAxles) &&
        Objects.equals(this.brakeCode, technicalRecord.brakeCode) &&
        Objects.equals(this.numberOfSeatbelts, technicalRecord.numberOfSeatbelts) &&
        Objects.equals(this.seatbeltInstallationApprovalDate, technicalRecord.seatbeltInstallationApprovalDate) &&
        Objects.equals(this.psvBrakes, technicalRecord.psvBrakes) &&
        Objects.equals(this.axles, technicalRecord.axles) &&
        Objects.equals(this.axlespacing, technicalRecord.axlespacing) &&
        Objects.equals(this.plates, technicalRecord.plates) &&
        Objects.equals(this.dtpNumber, technicalRecord.dtpNumber) &&
        Objects.equals(this.loadSensingValve, technicalRecord.loadSensingValve) &&
        Objects.equals(this.antilockBrakingSystem, technicalRecord.antilockBrakingSystem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recordtype, createdAt, lastUpdatedAt, makeModel, functionCode, offRoad, numberOfWheelsDriven, emissionsLimit, departmentalVehicleMarker, alterationMarker, vehicleClass, variantVersionNumber, grossEecWeight, trainEecWeight, maxTrainEecWeight, manufactureYear, regnDate, firstUseDate, coifDate, ntaNumber, coifSerialNumber, coifCertifierName, approvalType, approvalTypeNumber, variantNumber, conversionRefNo, seatsLowerDeck, seatsUpperDeck, standingCapacity, speedRestriction, speedLimiterMrk, tachoExemptMrk, dispensations, remarks, reasonForCreation, statusCode, unladenWeight, grossKerbWeight, grossLadenWeight, grossGbWeight, grossDesignWeight, trainGbWeight, trainDesignWeight, maxTrainGbWeight, maxTrainDesignWeight, maxLoadOnCoupling, frameDescription, tyreUseCode, roadFriendly, drawbarCouplingFitted, euroStandard, suspensionType, couplingType, length, height, width, frontAxleTo5thWheelMin, frontAxleTo5thWheelMax, frontAxleTo5thWheelCouplingMin, frontAxleTo5thWheelCouplingMax, frontAxleToRearAxle, rearAxleToRearTrl, couplingCentreToRearAxleMin, couplingCentreToRearAxleMax, couplingCentreToRearTrlMin, couplingCentreToRearTrlMax, centreOfRearmostAxleToRearOfTrl, notes, purchaserNotes, manufacturerNotes, noOfAxles, brakeCode, numberOfSeatbelts, seatbeltInstallationApprovalDate, psvBrakes, axles, axlespacing, plates, dtpNumber, loadSensingValve, antilockBrakingSystem);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TechnicalRecord {\n");
    
    sb.append("    recordtype: ").append(toIndentedString(recordtype)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    lastUpdatedAt: ").append(toIndentedString(lastUpdatedAt)).append("\n");
    sb.append("    makeModel: ").append(toIndentedString(makeModel)).append("\n");
    sb.append("    functionCode: ").append(toIndentedString(functionCode)).append("\n");
    sb.append("    offRoad: ").append(toIndentedString(offRoad)).append("\n");
    sb.append("    numberOfWheelsDriven: ").append(toIndentedString(numberOfWheelsDriven)).append("\n");
    sb.append("    emissionsLimit: ").append(toIndentedString(emissionsLimit)).append("\n");
    sb.append("    departmentalVehicleMarker: ").append(toIndentedString(departmentalVehicleMarker)).append("\n");
    sb.append("    alterationMarker: ").append(toIndentedString(alterationMarker)).append("\n");
    sb.append("    vehicleClass: ").append(toIndentedString(vehicleClass)).append("\n");
    sb.append("    variantVersionNumber: ").append(toIndentedString(variantVersionNumber)).append("\n");
    sb.append("    grossEecWeight: ").append(toIndentedString(grossEecWeight)).append("\n");
    sb.append("    trainEecWeight: ").append(toIndentedString(trainEecWeight)).append("\n");
    sb.append("    maxTrainEecWeight: ").append(toIndentedString(maxTrainEecWeight)).append("\n");
    sb.append("    manufactureYear: ").append(toIndentedString(manufactureYear)).append("\n");
    sb.append("    regnDate: ").append(toIndentedString(regnDate)).append("\n");
    sb.append("    firstUseDate: ").append(toIndentedString(firstUseDate)).append("\n");
    sb.append("    coifDate: ").append(toIndentedString(coifDate)).append("\n");
    sb.append("    ntaNumber: ").append(toIndentedString(ntaNumber)).append("\n");
    sb.append("    coifSerialNumber: ").append(toIndentedString(coifSerialNumber)).append("\n");
    sb.append("    coifCertifierName: ").append(toIndentedString(coifCertifierName)).append("\n");
    sb.append("    approvalType: ").append(toIndentedString(approvalType)).append("\n");
    sb.append("    approvalTypeNumber: ").append(toIndentedString(approvalTypeNumber)).append("\n");
    sb.append("    variantNumber: ").append(toIndentedString(variantNumber)).append("\n");
    sb.append("    conversionRefNo: ").append(toIndentedString(conversionRefNo)).append("\n");
    sb.append("    seatsLowerDeck: ").append(toIndentedString(seatsLowerDeck)).append("\n");
    sb.append("    seatsUpperDeck: ").append(toIndentedString(seatsUpperDeck)).append("\n");
    sb.append("    standingCapacity: ").append(toIndentedString(standingCapacity)).append("\n");
    sb.append("    speedRestriction: ").append(toIndentedString(speedRestriction)).append("\n");
    sb.append("    speedLimiterMrk: ").append(toIndentedString(speedLimiterMrk)).append("\n");
    sb.append("    tachoExemptMrk: ").append(toIndentedString(tachoExemptMrk)).append("\n");
    sb.append("    dispensations: ").append(toIndentedString(dispensations)).append("\n");
    sb.append("    remarks: ").append(toIndentedString(remarks)).append("\n");
    sb.append("    reasonForCreation: ").append(toIndentedString(reasonForCreation)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    unladenWeight: ").append(toIndentedString(unladenWeight)).append("\n");
    sb.append("    grossKerbWeight: ").append(toIndentedString(grossKerbWeight)).append("\n");
    sb.append("    grossLadenWeight: ").append(toIndentedString(grossLadenWeight)).append("\n");
    sb.append("    grossGbWeight: ").append(toIndentedString(grossGbWeight)).append("\n");
    sb.append("    grossDesignWeight: ").append(toIndentedString(grossDesignWeight)).append("\n");
    sb.append("    trainGbWeight: ").append(toIndentedString(trainGbWeight)).append("\n");
    sb.append("    trainDesignWeight: ").append(toIndentedString(trainDesignWeight)).append("\n");
    sb.append("    maxTrainGbWeight: ").append(toIndentedString(maxTrainGbWeight)).append("\n");
    sb.append("    maxTrainDesignWeight: ").append(toIndentedString(maxTrainDesignWeight)).append("\n");
    sb.append("    maxLoadOnCoupling: ").append(toIndentedString(maxLoadOnCoupling)).append("\n");
    sb.append("    frameDescription: ").append(toIndentedString(frameDescription)).append("\n");
    sb.append("    tyreUseCode: ").append(toIndentedString(tyreUseCode)).append("\n");
    sb.append("    roadFriendly: ").append(toIndentedString(roadFriendly)).append("\n");
    sb.append("    drawbarCouplingFitted: ").append(toIndentedString(drawbarCouplingFitted)).append("\n");
    sb.append("    euroStandard: ").append(toIndentedString(euroStandard)).append("\n");
    sb.append("    suspensionType: ").append(toIndentedString(suspensionType)).append("\n");
    sb.append("    couplingType: ").append(toIndentedString(couplingType)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    frontAxleTo5thWheelMin: ").append(toIndentedString(frontAxleTo5thWheelMin)).append("\n");
    sb.append("    frontAxleTo5thWheelMax: ").append(toIndentedString(frontAxleTo5thWheelMax)).append("\n");
    sb.append("    frontAxleTo5thWheelCouplingMin: ").append(toIndentedString(frontAxleTo5thWheelCouplingMin)).append("\n");
    sb.append("    frontAxleTo5thWheelCouplingMax: ").append(toIndentedString(frontAxleTo5thWheelCouplingMax)).append("\n");
    sb.append("    frontAxleToRearAxle: ").append(toIndentedString(frontAxleToRearAxle)).append("\n");
    sb.append("    rearAxleToRearTrl: ").append(toIndentedString(rearAxleToRearTrl)).append("\n");
    sb.append("    couplingCentreToRearAxleMin: ").append(toIndentedString(couplingCentreToRearAxleMin)).append("\n");
    sb.append("    couplingCentreToRearAxleMax: ").append(toIndentedString(couplingCentreToRearAxleMax)).append("\n");
    sb.append("    couplingCentreToRearTrlMin: ").append(toIndentedString(couplingCentreToRearTrlMin)).append("\n");
    sb.append("    couplingCentreToRearTrlMax: ").append(toIndentedString(couplingCentreToRearTrlMax)).append("\n");
    sb.append("    centreOfRearmostAxleToRearOfTrl: ").append(toIndentedString(centreOfRearmostAxleToRearOfTrl)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    purchaserNotes: ").append(toIndentedString(purchaserNotes)).append("\n");
    sb.append("    manufacturerNotes: ").append(toIndentedString(manufacturerNotes)).append("\n");
    sb.append("    noOfAxles: ").append(toIndentedString(noOfAxles)).append("\n");
    sb.append("    brakeCode: ").append(toIndentedString(brakeCode)).append("\n");
    sb.append("    numberOfSeatbelts: ").append(toIndentedString(numberOfSeatbelts)).append("\n");
    sb.append("    seatbeltInstallationApprovalDate: ").append(toIndentedString(seatbeltInstallationApprovalDate)).append("\n");
    sb.append("    psvBrakes: ").append(toIndentedString(psvBrakes)).append("\n");
    sb.append("    axles: ").append(toIndentedString(axles)).append("\n");
    sb.append("    axlespacing: ").append(toIndentedString(axlespacing)).append("\n");
    sb.append("    plates: ").append(toIndentedString(plates)).append("\n");
    sb.append("    dtpNumber: ").append(toIndentedString(dtpNumber)).append("\n");
    sb.append("    loadSensingValve: ").append(toIndentedString(loadSensingValve)).append("\n");
    sb.append("    antilockBrakingSystem: ").append(toIndentedString(antilockBrakingSystem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
