/*
 * Vehicle Enquiry Service Swagger
 * This is the CVS API for showing details of heavy goods vehicles and their associated test result.
 *
 * OpenAPI spec version: 1.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.enquiry;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * TestStation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T17:16:44.237Z[GMT]")
public class TestStation {
  @SerializedName("stationNumber")
  private String stationNumber = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("type")
  private String type = null;

  public TestStation stationNumber(String stationNumber) {
    this.stationNumber = stationNumber;
    return this;
  }

   /**
   * Get stationNumber
   * @return stationNumber
  **/
  public String getStationNumber() {
    return stationNumber;
  }

  public void setStationNumber(String stationNumber) {
    this.stationNumber = stationNumber;
  }

  public TestStation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TestStation type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestStation testStation = (TestStation) o;
    return Objects.equals(this.stationNumber, testStation.stationNumber) &&
        Objects.equals(this.name, testStation.name) &&
        Objects.equals(this.type, testStation.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stationNumber, name, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestStation {\n");
    
    sb.append("    stationNumber: ").append(toIndentedString(stationNumber)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
