/*
 * Vehicle Enquiry Service Swagger
 * This is the CVS API for showing details of heavy goods vehicles and their associated test result.
 *
 * OpenAPI spec version: 1.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.enquiry;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * TestDefect
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T17:16:44.237Z[GMT]")
public class TestDefect {
  @SerializedName("defect")
  private Defect defect = null;

  @SerializedName("location")
  private Location location = null;

  @SerializedName("notes")
  private String notes = null;

  @SerializedName("prs")
  private Boolean prs = null;

  @SerializedName("prohibitionIssued")
  private Integer prohibitionIssued = null;

  public TestDefect defect(Defect defect) {
    this.defect = defect;
    return this;
  }

   /**
   * Get defect
   * @return defect
  **/
  public Defect getDefect() {
    return defect;
  }

  public void setDefect(Defect defect) {
    this.defect = defect;
  }

  public TestDefect location(Location location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  public Location getLocation() {
    return location;
  }

  public void setLocation(Location location) {
    this.location = location;
  }

  public TestDefect notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public TestDefect prs(Boolean prs) {
    this.prs = prs;
    return this;
  }

   /**
   * Get prs
   * @return prs
  **/
  public Boolean isPrs() {
    return prs;
  }

  public void setPrs(Boolean prs) {
    this.prs = prs;
  }

  public TestDefect prohibitionIssued(Integer prohibitionIssued) {
    this.prohibitionIssued = prohibitionIssued;
    return this;
  }

   /**
   * Get prohibitionIssued
   * @return prohibitionIssued
  **/
  public Integer getProhibitionIssued() {
    return prohibitionIssued;
  }

  public void setProhibitionIssued(Integer prohibitionIssued) {
    this.prohibitionIssued = prohibitionIssued;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestDefect testDefect = (TestDefect) o;
    return Objects.equals(this.defect, testDefect.defect) &&
        Objects.equals(this.location, testDefect.location) &&
        Objects.equals(this.notes, testDefect.notes) &&
        Objects.equals(this.prs, testDefect.prs) &&
        Objects.equals(this.prohibitionIssued, testDefect.prohibitionIssued);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defect, location, notes, prs, prohibitionIssued);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestDefect {\n");
    
    sb.append("    defect: ").append(toIndentedString(defect)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    prs: ").append(toIndentedString(prs)).append("\n");
    sb.append("    prohibitionIssued: ").append(toIndentedString(prohibitionIssued)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
