/*
 * Vehicle Enquiry Service Swagger
 * This is the CVS API for showing details of heavy goods vehicles and their associated test result.
 *
 * OpenAPI spec version: 1.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.enquiry;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * Tyre
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T17:16:44.237Z[GMT]")
public class Tyre {
  @SerializedName("tyreSize")
  private String tyreSize = null;

  @SerializedName("plyRating")
  private String plyRating = null;

  @SerializedName("fitmentCode")
  private String fitmentCode = null;

  @SerializedName("dataTrAxles")
  private String dataTrAxles = null;

  @SerializedName("speedCategorySymbol")
  private String speedCategorySymbol = null;

  @SerializedName("tyreCode")
  private Integer tyreCode = null;

  public Tyre tyreSize(String tyreSize) {
    this.tyreSize = tyreSize;
    return this;
  }

   /**
   * Get tyreSize
   * @return tyreSize
  **/
  public String getTyreSize() {
    return tyreSize;
  }

  public void setTyreSize(String tyreSize) {
    this.tyreSize = tyreSize;
  }

  public Tyre plyRating(String plyRating) {
    this.plyRating = plyRating;
    return this;
  }

   /**
   * Get plyRating
   * @return plyRating
  **/
  public String getPlyRating() {
    return plyRating;
  }

  public void setPlyRating(String plyRating) {
    this.plyRating = plyRating;
  }

  public Tyre fitmentCode(String fitmentCode) {
    this.fitmentCode = fitmentCode;
    return this;
  }

   /**
   * Get fitmentCode
   * @return fitmentCode
  **/
  public String getFitmentCode() {
    return fitmentCode;
  }

  public void setFitmentCode(String fitmentCode) {
    this.fitmentCode = fitmentCode;
  }

  public Tyre dataTrAxles(String dataTrAxles) {
    this.dataTrAxles = dataTrAxles;
    return this;
  }

   /**
   * Get dataTrAxles
   * @return dataTrAxles
  **/
  public String getDataTrAxles() {
    return dataTrAxles;
  }

  public void setDataTrAxles(String dataTrAxles) {
    this.dataTrAxles = dataTrAxles;
  }

  public Tyre speedCategorySymbol(String speedCategorySymbol) {
    this.speedCategorySymbol = speedCategorySymbol;
    return this;
  }

   /**
   * Get speedCategorySymbol
   * @return speedCategorySymbol
  **/
  public String getSpeedCategorySymbol() {
    return speedCategorySymbol;
  }

  public void setSpeedCategorySymbol(String speedCategorySymbol) {
    this.speedCategorySymbol = speedCategorySymbol;
  }

  public Tyre tyreCode(Integer tyreCode) {
    this.tyreCode = tyreCode;
    return this;
  }

   /**
   * Get tyreCode
   * @return tyreCode
  **/
  public Integer getTyreCode() {
    return tyreCode;
  }

  public void setTyreCode(Integer tyreCode) {
    this.tyreCode = tyreCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tyre tyre = (Tyre) o;
    return Objects.equals(this.tyreSize, tyre.tyreSize) &&
        Objects.equals(this.plyRating, tyre.plyRating) &&
        Objects.equals(this.fitmentCode, tyre.fitmentCode) &&
        Objects.equals(this.dataTrAxles, tyre.dataTrAxles) &&
        Objects.equals(this.speedCategorySymbol, tyre.speedCategorySymbol) &&
        Objects.equals(this.tyreCode, tyre.tyreCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tyreSize, plyRating, fitmentCode, dataTrAxles, speedCategorySymbol, tyreCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tyre {\n");
    
    sb.append("    tyreSize: ").append(toIndentedString(tyreSize)).append("\n");
    sb.append("    plyRating: ").append(toIndentedString(plyRating)).append("\n");
    sb.append("    fitmentCode: ").append(toIndentedString(fitmentCode)).append("\n");
    sb.append("    dataTrAxles: ").append(toIndentedString(dataTrAxles)).append("\n");
    sb.append("    speedCategorySymbol: ").append(toIndentedString(speedCategorySymbol)).append("\n");
    sb.append("    tyreCode: ").append(toIndentedString(tyreCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
