/*
 * Vehicle Enquiry Service Swagger
 * This is the CVS API for showing details of heavy goods vehicles and their associated test result.
 *
 * OpenAPI spec version: 1.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.enquiry;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * Vehicle
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T17:16:44.237Z[GMT]")
public class Vehicle {
  @SerializedName("system_number")
  private String systemNumber = null;

  @SerializedName("vrm_trm")
  private String vrmTrm = null;

  @SerializedName("trailer_id")
  private String trailerId = null;

  @SerializedName("vin")
  private String vin = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("technicalrecords")
  private TechnicalRecords technicalrecords = null;

  public Vehicle systemNumber(String systemNumber) {
    this.systemNumber = systemNumber;
    return this;
  }

   /**
   * Get systemNumber
   * @return systemNumber
  **/
  public String getSystemNumber() {
    return systemNumber;
  }

  public void setSystemNumber(String systemNumber) {
    this.systemNumber = systemNumber;
  }

  public Vehicle vrmTrm(String vrmTrm) {
    this.vrmTrm = vrmTrm;
    return this;
  }

   /**
   * Get vrmTrm
   * @return vrmTrm
  **/
  public String getVrmTrm() {
    return vrmTrm;
  }

  public void setVrmTrm(String vrmTrm) {
    this.vrmTrm = vrmTrm;
  }

  public Vehicle trailerId(String trailerId) {
    this.trailerId = trailerId;
    return this;
  }

   /**
   * Get trailerId
   * @return trailerId
  **/
  public String getTrailerId() {
    return trailerId;
  }

  public void setTrailerId(String trailerId) {
    this.trailerId = trailerId;
  }

  public Vehicle vin(String vin) {
    this.vin = vin;
    return this;
  }

   /**
   * Get vin
   * @return vin
  **/
  public String getVin() {
    return vin;
  }

  public void setVin(String vin) {
    this.vin = vin;
  }

  public Vehicle createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public Vehicle technicalrecords(TechnicalRecords technicalrecords) {
    this.technicalrecords = technicalrecords;
    return this;
  }

   /**
   * Get technicalrecords
   * @return technicalrecords
  **/
  public TechnicalRecords getTechnicalrecords() {
    return technicalrecords;
  }

  public void setTechnicalrecords(TechnicalRecords technicalrecords) {
    this.technicalrecords = technicalrecords;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vehicle vehicle = (Vehicle) o;
    return Objects.equals(this.systemNumber, vehicle.systemNumber) &&
        Objects.equals(this.vrmTrm, vehicle.vrmTrm) &&
        Objects.equals(this.trailerId, vehicle.trailerId) &&
        Objects.equals(this.vin, vehicle.vin) &&
        Objects.equals(this.createdAt, vehicle.createdAt) &&
        Objects.equals(this.technicalrecords, vehicle.technicalrecords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(systemNumber, vrmTrm, trailerId, vin, createdAt, technicalrecords);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vehicle {\n");
    
    sb.append("    systemNumber: ").append(toIndentedString(systemNumber)).append("\n");
    sb.append("    vrmTrm: ").append(toIndentedString(vrmTrm)).append("\n");
    sb.append("    trailerId: ").append(toIndentedString(trailerId)).append("\n");
    sb.append("    vin: ").append(toIndentedString(vin)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    technicalrecords: ").append(toIndentedString(technicalrecords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
