package vott.databaseModels;

import lombok.Data;

@Data
public class TechnicalRecord {

//    private Integer vehicleID;
//    private String recordCompleteness;
//    private String createdAt;
//    private String lastUpdatedAt;
//    private Integer makeModelID;
//    private String functionCode;
//    private Integer offRoad;
//    private Integer numberOfWheelsDriven;
//    private String emissionsLimit;
//    private Integer departmentalVehicleMarker;
//    private Integer alterationMarker;
//    private Integer vehicleClassID;
//    private String variantVersionNumber;
//    private Integer grossEecWeight;
//    private Integer trainEecWeight;
//    private Integer maxTrainEecWeight;
//    private Integer applicantDetailID;
//    private Integer purchaserDetailID;
//    private Integer manufacturerDetailID;
//    private String manufactureYear;
//    private String regnDate;
//    private String firstUseDate;
//    private String coifDate;
//    private String ntaNumber;
//    private String coifSerialNumber;
//    private String coifCertifierName;
//    private String approvalType;
//    private String approvalTypeNumber;
//    private String variantNumber;
//    private String conversionRefNo;
//    private Integer seatsLowerDeck;
//    private Integer seatsUpperDeck;
//    private Integer standingCapacity;
//    private Integer speedRestriction;
//    private Integer speedLimiterMrk;
//    private Integer tachoExemptMrk;
//    private String dispensations;
//    private String remarks;
//    private String reasonForCreation;
//    private String statusCode;
//    private Integer unladenWeight;
//    private Integer grossKerbWeight;
//    private Integer grossLadenWeight;
//    private Integer grossGbWeight;
//    private Integer grossDesignWeight;
//    private Integer trainGbWeight;
//    private Integer trainDesignWeight;
//    private Integer maxTrainGbWeight;
//    private Integer maxTrainDesignWeight;
//    private Integer maxLoadOnCoupling;
//    private String frameDescription;
//    private String tyreUseCode;
//    private Integer roadFriendly;
//    private Integer drawbarCouplingFitted;
//    private String euroStandard;
//    private String suspensionType;
//    private String couplingType;
//    private Integer length;
//    private Integer height;
//    private Integer width;
//    private Integer frontAxleTo5thWheelMin;
//    private Integer frontAxleTo5thWheelMax;
//    private Integer frontAxleTo5thWheelCouplingMin;
//    private Integer frontAxleTo5thWheelCouplingMax;
//    private Integer frontAxleToRearAxle;
//    private Integer rearAxleToRearTrl;
//    private Integer couplingCenterToRearAxleMin;
//    private Integer couplingCenterToRearAxleMax;
//    private Integer couplingCenterToRearTrlMin;
//    private Integer couplingCenterToRearTrlMax;
//    private Integer centreOfRearmostAxleToRearOfTrl;
//    private String notes;
//    private String purchaserNotes;
//    private String manufacturerNotes;
//    private Integer noOfAxles;
//    private String brakeCode;
//    private String brakes_dtpNumber;
//    private Integer brakes_loadSensingValve;
//    private Integer brakes_antilockBrakingSystem;
//    private Integer createdByID;
//    private Integer lastUpdatedByID;
//    private String updateType;
//    private String numberOfSeatbelts;
//    private String seatbeltInstallationApprovalDate;

    private String vehicleID;
    private String recordCompleteness;
    private String createdAt;
    private String lastUpdatedAt;
    private String makeModelID;
    private String functionCode;
    private String offRoad;
    private String numberOfWheelsDriven;
    private String emissionsLimit;
    private String departmentalVehicleMarker;
    private String alterationMarker;
    private String vehicleClassID;
    private String variantVersionNumber;
    private String grossEecWeight;
    private String trainEecWeight;
    private String maxTrainEecWeight;
    private String applicantDetailID;
    private String purchaserDetailID;
    private String manufacturerDetailID;
    private String manufactureYear;
    private String regnDate;
    private String firstUseDate;
    private String coifDate;
    private String ntaNumber;
    private String coifSerialNumber;
    private String coifCertifierName;
    private String approvalType;
    private String approvalTypeNumber;
    private String variantNumber;
    private String conversionRefNo;
    private String seatsLowerDeck;
    private String seatsUpperDeck;
    private String standingCapacity;
    private String speedRestriction;
    private String speedLimiterMrk;
    private String tachoExemptMrk;
    private String dispensations;
    private String remarks;
    private String reasonForCreation;
    private String statusCode;
    private String unladenWeight;
    private String grossKerbWeight;
    private String grossLadenWeight;
    private String grossGbWeight;
    private String grossDesignWeight;
    private String trainGbWeight;
    private String trainDesignWeight;
    private String maxTrainGbWeight;
    private String maxTrainDesignWeight;
    private String maxLoadOnCoupling;
    private String frameDescription;
    private String tyreUseCode;
    private String roadFriendly;
    private String drawbarCouplingFitted;
    private String euroStandard;
    private String suspensionType;
    private String couplingType;
    private String length;
    private String height;
    private String width;
    private String frontAxleTo5thWheelMin;
    private String frontAxleTo5thWheelMax;
    private String frontAxleTo5thWheelCouplingMin;
    private String frontAxleTo5thWheelCouplingMax;
    private String frontAxleToRearAxle;
    private String rearAxleToRearTrl;
    private String couplingCenterToRearAxleMin;
    private String couplingCenterToRearAxleMax;
    private String couplingCenterToRearTrlMin;
    private String couplingCenterToRearTrlMax;
    private String centreOfRearmostAxleToRearOfTrl;
    private String notes;
    private String purchaserNotes;
    private String manufacturerNotes;
    private String noOfAxles;
    private String brakeCode;
    private String brakes_dtpNumber;
    private String brakes_loadSensingValve;
    private String brakes_antilockBrakingSystem;
    private String createdByID;
    private String lastUpdatedByID;
    private String updateType;
    private String numberOfSeatbelts;
    private String seatbeltInstallationApprovalDate;

}
