/*
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bpecete@deloittece.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.techrecords;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * AdrDetailsApplicantDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T13:30:43.231Z[GMT]")
public class AdrDetailsApplicantDetails {
  @SerializedName("name")
  private String name = null;

  @SerializedName("street")
  private String street = null;

  @SerializedName("town")
  private String town = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("postcode")
  private String postcode = null;

  public AdrDetailsApplicantDetails name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
    public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AdrDetailsApplicantDetails street(String street) {
    this.street = street;
    return this;
  }

   /**
   * Get street
   * @return street
  **/
    public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.street = street;
  }

  public AdrDetailsApplicantDetails town(String town) {
    this.town = town;
    return this;
  }

   /**
   * Get town
   * @return town
  **/
    public String getTown() {
    return town;
  }

  public void setTown(String town) {
    this.town = town;
  }

  public AdrDetailsApplicantDetails city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
    public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public AdrDetailsApplicantDetails postcode(String postcode) {
    this.postcode = postcode;
    return this;
  }

   /**
   * Get postcode
   * @return postcode
  **/
    public String getPostcode() {
    return postcode;
  }

  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdrDetailsApplicantDetails adrDetailsApplicantDetails = (AdrDetailsApplicantDetails) o;
    return Objects.equals(this.name, adrDetailsApplicantDetails.name) &&
        Objects.equals(this.street, adrDetailsApplicantDetails.street) &&
        Objects.equals(this.town, adrDetailsApplicantDetails.town) &&
        Objects.equals(this.city, adrDetailsApplicantDetails.city) &&
        Objects.equals(this.postcode, adrDetailsApplicantDetails.postcode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, street, town, city, postcode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdrDetailsApplicantDetails {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    town: ").append(toIndentedString(town)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
