/*
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bpecete@deloittece.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.techrecords;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * AdrDetailsTank
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T13:30:43.231Z[GMT]")
public class AdrDetailsTank {
  @SerializedName("tankDetails")
  private AdrDetailsTankTankDetails tankDetails = null;

  @SerializedName("tankStatement")
  private AdrDetailsTankTankStatement tankStatement = null;

  public AdrDetailsTank tankDetails(AdrDetailsTankTankDetails tankDetails) {
    this.tankDetails = tankDetails;
    return this;
  }

   /**
   * Get tankDetails
   * @return tankDetails
  **/
    public AdrDetailsTankTankDetails getTankDetails() {
    return tankDetails;
  }

  public void setTankDetails(AdrDetailsTankTankDetails tankDetails) {
    this.tankDetails = tankDetails;
  }

  public AdrDetailsTank tankStatement(AdrDetailsTankTankStatement tankStatement) {
    this.tankStatement = tankStatement;
    return this;
  }

   /**
   * Get tankStatement
   * @return tankStatement
  **/
    public AdrDetailsTankTankStatement getTankStatement() {
    return tankStatement;
  }

  public void setTankStatement(AdrDetailsTankTankStatement tankStatement) {
    this.tankStatement = tankStatement;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdrDetailsTank adrDetailsTank = (AdrDetailsTank) o;
    return Objects.equals(this.tankDetails, adrDetailsTank.tankDetails) &&
        Objects.equals(this.tankStatement, adrDetailsTank.tankStatement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tankDetails, tankStatement);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdrDetailsTank {\n");
    
    sb.append("    tankDetails: ").append(toIndentedString(tankDetails)).append("\n");
    sb.append("    tankStatement: ").append(toIndentedString(tankStatement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
