/*
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bpecete@deloittece.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.techrecords;

import com.google.gson.annotations.SerializedName;
import java.time.LocalDate;

import java.util.Objects;

/**
 * AdrDetailsVehicleDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T13:30:43.231Z[GMT]")
public class AdrDetailsVehicleDetails {
  @SerializedName("type")
  private String type = null;

  @SerializedName("approvalDate")
  private LocalDate approvalDate = null;

  public AdrDetailsVehicleDetails type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Mandatory. Users must select ONE of these. Users cannot select less/more
   * @return type
  **/
    public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public AdrDetailsVehicleDetails approvalDate(LocalDate approvalDate) {
    this.approvalDate = approvalDate;
    return this;
  }

   /**
   * Date (YYYY-MM-DD)
   * @return approvalDate
  **/
    public LocalDate getApprovalDate() {
    return approvalDate;
  }

  public void setApprovalDate(LocalDate approvalDate) {
    this.approvalDate = approvalDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdrDetailsVehicleDetails adrDetailsVehicleDetails = (AdrDetailsVehicleDetails) o;
    return Objects.equals(this.type, adrDetailsVehicleDetails.type) &&
        Objects.equals(this.approvalDate, adrDetailsVehicleDetails.approvalDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, approvalDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdrDetailsVehicleDetails {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    approvalDate: ").append(toIndentedString(approvalDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
