/*
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bpecete@deloittece.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.techrecords;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * BrakeForceWheelsUpToHalfLocked
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T13:30:43.231Z[GMT]")
public class BrakeForceWheelsUpToHalfLocked {
  @SerializedName("serviceBrakeForceB")
  private BigDecimal serviceBrakeForceB = null;

  @SerializedName("secondaryBrakeForceB")
  private BigDecimal secondaryBrakeForceB = null;

  @SerializedName("parkingBrakeForceB")
  private BigDecimal parkingBrakeForceB = null;

  public BrakeForceWheelsUpToHalfLocked serviceBrakeForceB(BigDecimal serviceBrakeForceB) {
    this.serviceBrakeForceB = serviceBrakeForceB;
    return this;
  }

   /**
   * Used only for PSV
   * maximum: 99999
   * @return serviceBrakeForceB
  **/
    public BigDecimal getServiceBrakeForceB() {
    return serviceBrakeForceB;
  }

  public void setServiceBrakeForceB(BigDecimal serviceBrakeForceB) {
    this.serviceBrakeForceB = serviceBrakeForceB;
  }

  public BrakeForceWheelsUpToHalfLocked secondaryBrakeForceB(BigDecimal secondaryBrakeForceB) {
    this.secondaryBrakeForceB = secondaryBrakeForceB;
    return this;
  }

   /**
   * Used only for PSV
   * maximum: 99999
   * @return secondaryBrakeForceB
  **/
    public BigDecimal getSecondaryBrakeForceB() {
    return secondaryBrakeForceB;
  }

  public void setSecondaryBrakeForceB(BigDecimal secondaryBrakeForceB) {
    this.secondaryBrakeForceB = secondaryBrakeForceB;
  }

  public BrakeForceWheelsUpToHalfLocked parkingBrakeForceB(BigDecimal parkingBrakeForceB) {
    this.parkingBrakeForceB = parkingBrakeForceB;
    return this;
  }

   /**
   * Used only for PSV
   * maximum: 99999
   * @return parkingBrakeForceB
  **/
    public BigDecimal getParkingBrakeForceB() {
    return parkingBrakeForceB;
  }

  public void setParkingBrakeForceB(BigDecimal parkingBrakeForceB) {
    this.parkingBrakeForceB = parkingBrakeForceB;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrakeForceWheelsUpToHalfLocked brakeForceWheelsUpToHalfLocked = (BrakeForceWheelsUpToHalfLocked) o;
    return Objects.equals(this.serviceBrakeForceB, brakeForceWheelsUpToHalfLocked.serviceBrakeForceB) &&
        Objects.equals(this.secondaryBrakeForceB, brakeForceWheelsUpToHalfLocked.secondaryBrakeForceB) &&
        Objects.equals(this.parkingBrakeForceB, brakeForceWheelsUpToHalfLocked.parkingBrakeForceB);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceBrakeForceB, secondaryBrakeForceB, parkingBrakeForceB);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrakeForceWheelsUpToHalfLocked {\n");
    
    sb.append("    serviceBrakeForceB: ").append(toIndentedString(serviceBrakeForceB)).append("\n");
    sb.append("    secondaryBrakeForceB: ").append(toIndentedString(secondaryBrakeForceB)).append("\n");
    sb.append("    parkingBrakeForceB: ").append(toIndentedString(parkingBrakeForceB)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
