/*
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bpecete@deloittece.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.techrecords;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * BrakeForceWheelsNotLocked
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T13:30:43.231Z[GMT]")
public class BrakeForceWheelsNotLocked {
  @SerializedName("serviceBrakeForceA")
  private BigDecimal serviceBrakeForceA = null;

  @SerializedName("secondaryBrakeForceA")
  private BigDecimal secondaryBrakeForceA = null;

  @SerializedName("parkingBrakeForceA")
  private BigDecimal parkingBrakeForceA = null;

  public BrakeForceWheelsNotLocked serviceBrakeForceA(BigDecimal serviceBrakeForceA) {
    this.serviceBrakeForceA = serviceBrakeForceA;
    return this;
  }

   /**
   * Used only for PSV
   * maximum: 99999
   * @return serviceBrakeForceA
  **/
    public BigDecimal getServiceBrakeForceA() {
    return serviceBrakeForceA;
  }

  public void setServiceBrakeForceA(BigDecimal serviceBrakeForceA) {
    this.serviceBrakeForceA = serviceBrakeForceA;
  }

  public BrakeForceWheelsNotLocked secondaryBrakeForceA(BigDecimal secondaryBrakeForceA) {
    this.secondaryBrakeForceA = secondaryBrakeForceA;
    return this;
  }

   /**
   * Used only for PSV
   * maximum: 99999
   * @return secondaryBrakeForceA
  **/
    public BigDecimal getSecondaryBrakeForceA() {
    return secondaryBrakeForceA;
  }

  public void setSecondaryBrakeForceA(BigDecimal secondaryBrakeForceA) {
    this.secondaryBrakeForceA = secondaryBrakeForceA;
  }

  public BrakeForceWheelsNotLocked parkingBrakeForceA(BigDecimal parkingBrakeForceA) {
    this.parkingBrakeForceA = parkingBrakeForceA;
    return this;
  }

   /**
   * Used only for PSV
   * maximum: 99999
   * @return parkingBrakeForceA
  **/
    public BigDecimal getParkingBrakeForceA() {
    return parkingBrakeForceA;
  }

  public void setParkingBrakeForceA(BigDecimal parkingBrakeForceA) {
    this.parkingBrakeForceA = parkingBrakeForceA;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrakeForceWheelsNotLocked brakeForceWheelsNotLocked = (BrakeForceWheelsNotLocked) o;
    return Objects.equals(this.serviceBrakeForceA, brakeForceWheelsNotLocked.serviceBrakeForceA) &&
        Objects.equals(this.secondaryBrakeForceA, brakeForceWheelsNotLocked.secondaryBrakeForceA) &&
        Objects.equals(this.parkingBrakeForceA, brakeForceWheelsNotLocked.parkingBrakeForceA);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceBrakeForceA, secondaryBrakeForceA, parkingBrakeForceA);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrakeForceWheelsNotLocked {\n");
    
    sb.append("    serviceBrakeForceA: ").append(toIndentedString(serviceBrakeForceA)).append("\n");
    sb.append("    secondaryBrakeForceA: ").append(toIndentedString(secondaryBrakeForceA)).append("\n");
    sb.append("    parkingBrakeForceA: ").append(toIndentedString(parkingBrakeForceA)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
