/*
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bpecete@deloittece.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.techrecords;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Applicable only to ADR details. Returned only if query param \&quot;metadata\&quot; &#x3D; \&quot;true\&quot;, otherwise not returned
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T13:30:43.231Z[GMT]")
public class Metadata {
  @SerializedName("makeAndChassisMakeFe")
  private List<String> makeAndChassisMakeFe = null;

  @SerializedName("bodyMakeFe")
  private List<String> bodyMakeFe = null;

  @SerializedName("adrDetails")
  private MetadataAdrDetails adrDetails = null;

  public Metadata makeAndChassisMakeFe(List<String> makeAndChassisMakeFe) {
    this.makeAndChassisMakeFe = makeAndChassisMakeFe;
    return this;
  }

  public Metadata addMakeAndChassisMakeFeItem(String makeAndChassisMakeFeItem) {
    if (this.makeAndChassisMakeFe == null) {
      this.makeAndChassisMakeFe = new ArrayList<String>();
    }
    this.makeAndChassisMakeFe.add(makeAndChassisMakeFeItem);
    return this;
  }

   /**
   * makeFe and chassisMakeFe fields have the same value. Combining them into a field for now so we don&#x27;t send the same list twice.
   * @return makeAndChassisMakeFe
  **/
    public List<String> getMakeAndChassisMakeFe() {
    return makeAndChassisMakeFe;
  }

  public void setMakeAndChassisMakeFe(List<String> makeAndChassisMakeFe) {
    this.makeAndChassisMakeFe = makeAndChassisMakeFe;
  }

  public Metadata bodyMakeFe(List<String> bodyMakeFe) {
    this.bodyMakeFe = bodyMakeFe;
    return this;
  }

  public Metadata addBodyMakeFeItem(String bodyMakeFeItem) {
    if (this.bodyMakeFe == null) {
      this.bodyMakeFe = new ArrayList<String>();
    }
    this.bodyMakeFe.add(bodyMakeFeItem);
    return this;
  }

   /**
   * Get bodyMakeFe
   * @return bodyMakeFe
  **/
    public List<String> getBodyMakeFe() {
    return bodyMakeFe;
  }

  public void setBodyMakeFe(List<String> bodyMakeFe) {
    this.bodyMakeFe = bodyMakeFe;
  }

  public Metadata adrDetails(MetadataAdrDetails adrDetails) {
    this.adrDetails = adrDetails;
    return this;
  }

   /**
   * Get adrDetails
   * @return adrDetails
  **/
    public MetadataAdrDetails getAdrDetails() {
    return adrDetails;
  }

  public void setAdrDetails(MetadataAdrDetails adrDetails) {
    this.adrDetails = adrDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Metadata metadata = (Metadata) o;
    return Objects.equals(this.makeAndChassisMakeFe, metadata.makeAndChassisMakeFe) &&
        Objects.equals(this.bodyMakeFe, metadata.bodyMakeFe) &&
        Objects.equals(this.adrDetails, metadata.adrDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(makeAndChassisMakeFe, bodyMakeFe, adrDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Metadata {\n");
    
    sb.append("    makeAndChassisMakeFe: ").append(toIndentedString(makeAndChassisMakeFe)).append("\n");
    sb.append("    bodyMakeFe: ").append(toIndentedString(bodyMakeFe)).append("\n");
    sb.append("    adrDetails: ").append(toIndentedString(adrDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
