/*
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bpecete@deloittece.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.techrecords;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * TechRecordDimensionsAxleSpacing
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T13:30:43.231Z[GMT]")
public class TechRecordDimensionsAxleSpacing {
  @SerializedName("axles")
  private String axles = null;

  @SerializedName("value")
  private BigDecimal value = null;

  public TechRecordDimensionsAxleSpacing axles(String axles) {
    this.axles = axles;
    return this;
  }

   /**
   * Get axles
   * @return axles
  **/
    public String getAxles() {
    return axles;
  }

  public void setAxles(String axles) {
    this.axles = axles;
  }

  public TechRecordDimensionsAxleSpacing value(BigDecimal value) {
    this.value = value;
    return this;
  }

   /**
   * Optional for HGV
   * maximum: 99999
   * @return value
  **/
    public BigDecimal getValue() {
    return value;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TechRecordDimensionsAxleSpacing techRecordDimensionsAxleSpacing = (TechRecordDimensionsAxleSpacing) o;
    return Objects.equals(this.axles, techRecordDimensionsAxleSpacing.axles) &&
        Objects.equals(this.value, techRecordDimensionsAxleSpacing.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(axles, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TechRecordDimensionsAxleSpacing {\n");
    
    sb.append("    axles: ").append(toIndentedString(axles)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
