/*
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bpecete@deloittece.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.models.dto.techrecords;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * TechRecordArchiveAndProvisionalPayloadMsUserDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-13T13:30:43.231Z[GMT]")
public class TechRecordArchiveAndProvisionalPayloadMsUserDetails {
  @SerializedName("msUser")
  private String msUser = null;

  @SerializedName("msOid")
  private String msOid = null;

  public TechRecordArchiveAndProvisionalPayloadMsUserDetails msUser(String msUser) {
    this.msUser = msUser;
    return this;
  }

   /**
   * Get msUser
   * @return msUser
  **/
    public String getMsUser() {
    return msUser;
  }

  public void setMsUser(String msUser) {
    this.msUser = msUser;
  }

  public TechRecordArchiveAndProvisionalPayloadMsUserDetails msOid(String msOid) {
    this.msOid = msOid;
    return this;
  }

   /**
   * Get msOid
   * @return msOid
  **/
    public String getMsOid() {
    return msOid;
  }

  public void setMsOid(String msOid) {
    this.msOid = msOid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TechRecordArchiveAndProvisionalPayloadMsUserDetails techRecordArchiveAndProvisionalPayloadMsUserDetails = (TechRecordArchiveAndProvisionalPayloadMsUserDetails) o;
    return Objects.equals(this.msUser, techRecordArchiveAndProvisionalPayloadMsUserDetails.msUser) &&
        Objects.equals(this.msOid, techRecordArchiveAndProvisionalPayloadMsUserDetails.msOid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(msUser, msOid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TechRecordArchiveAndProvisionalPayloadMsUserDetails {\n");
    
    sb.append("    msUser: ").append(toIndentedString(msUser)).append("\n");
    sb.append("    msOid: ").append(toIndentedString(msOid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
